### ISSUE TITLE
Basic Question about title, description

### ISSUE THREAD

**Issue by epgunn** [sybrew/the-seo-framework#109]
This is a question from a non-techie, so please answer in non-techie speak if you can. :-)

I installed SEO framework and used the data transfer plug-in. At the moment I have both Yoast and SEO framework on my site and would ideally like to delete yoast.

Here is my conundrum. When I post a new blog on Wordpress, Yoast provides the windows where i write my title, slug and description. I don't see an equivalent group of text boxes in the post from SEO framework, So what happens to all that data when I delete Yoast?  And where will I input those things? 

Thank you !

**Comment by LeBaux** [comment]
Generally, I answered how to switch [here](https://wordpress.org/support/topic/switching-from-yoast-to-this/#post-8921586). The boxes with meta description, title etc are there, right under wordpress editor. When you deactivate yoast, the data are still there - everything you have filled in is still stored in database. But when you delete yoast, that is when everything gets deleted.

Just import the data, deactivate yoast and check if they are correctly inside TSF boxes. If you have more questions or you don't know what I am talking about, ask and be very specific.

**Comment by sybrew** [comment]
@LeBaux Thanks for helping out! Keep up the good work 👍 

@epgunn I believe I sent you a mail before regarding this, it only took a little longer to respond because I was busy fixing a server bug 😄

## The mail states:
The SEO Framework disables most of its user interface if Yoast or another big SEO plugin is found (to prevent conflicts).

The SEO Framework also has its own user interface, the screenshots are found on the plugin homepage:
https://wordpress.org/plugins/autodescription/#screenshots

The SEO Framework has these options for each page, post, and public custom post type:
-	Custom Title
-	Custom Description
-	Custom Canonical URL (advanced)
-	Robots settings (noindex, nofollow, noarchive)
-	Local Search Exclusion (“example.com/?s=my+search+query” won’t find that page if it’s enabled)
-	Custom Redirect URL (this is Premium-only in Yoast)
-	Custom Social Image (with optimal size cropping, and caching for Facebook and Twitter)

Note that some of those things can be automatically filled in, so it saves you a lot of time.

**Comment by epgunn** [comment]
thank you both. I think this answers my questions. and I really apprecaite it. 

So just to be clear. If I transferred my data and when I disable Yoast it all looks ok, does that mean it’s probablly safe to delete it? Or do I need to keep Yoast on the backend, deactivated?


Eileen P. Gunn
FamiliesGo!
www.familiesgotravel.com
#MOMtravelchat Twitter parties
Custom content outsourcing
familiesgo@gmail.com
917.533.2197

**Comment by LeBaux** [comment]
It should be safe to deactivate the yoast SEO, but there is no rush to delete it. You can monitor your SERP positions, if you do not have other tools you can use [whatsmyserp.com](http://www.whatsmyserp.com/serpcheck.php). It is free and rather basic tool, but it gets the job done. As you said, you are not a techie, and even if you are, there is something that could go wrong even if you are SEO expert. Keep an eye on your SERP positions of your most important phrases and keywords. If you do not see any changes in 3 months, you are pretty safe to delete the yoast plugin with all data.

Note that I am really advising very cautious approach, and this might look like planing for failure, but in reality, I am just giving you general SEO advice - track what you are doing, keep the log of changes and backup to retrace your steps in case of any problems.

**Comment by sybrew** [comment]
If you're not using a plugin, you should &mdash; nay, must delete it.
Summarized: it's not only safe to delete, it's safer.

Although this is most likely not the case with Yoast's plugins, plugin files can have open hooks or headers hackers can use to penetrate your website.
I won't show you a real-life scenario, but it's perfectly common to attack otherwise never used files on websites.

Anyway, I digress... here's something much more tactile:
On deactivation, Yoast SEO clears its cache and capabilities.
On delete, Yoast SEO, like many other plugins, does nothing. Which is perfectly fine.

This means the following: All your old data is left intact, exactly how you left it. So, you can easily re-install the plugin if wished for.
This also means this: Your website is actually faster with less plugins available. The devil is in the details, but it basically comes down to that WordPress needs to do less checks.

Just be sure to delete the unwanted plugins through the WordPress interface... because WordPress actually keeps tracks of those in the database, and then silently goes "oh no!" when you delete one through FTP.
