### ISSUE TITLE
multiple sitemaps in SEO Framework

### ISSUE THREAD

**Issue by epgunn** [sybrew/the-seo-framework#111]
I had 5 sitemaps submitted to Google: a general sitemap and then one each for pages, posts, tags and and categories. After switching over to SEO Framework, Google can no longer find them and when I click on them I get my 404 page. I submitted the general sitemap that SEO framework generated. But that means google is indexing 363 items vs 8,000 items before. Do those extra items enhance my SEO? Do I need them? if so, how do i recreate them in Framework?  If I don't need them should I delete them from webmaster so it doesn't keep trying to read them?

**Comment by LeBaux** [comment]
Hi @epgunn, interesting question 🤔 Please look at this[ short presentation about multiple sitemaps](https://www.slideshare.net/LaurentMuellender/advanced-seo-through-multiple-xml-sitemaps). Generally speaking, sitemaps just help google to crawl your website easier. In 99% of cases you want to split them only if they are too big. 

So, even if you have no sitemaps and you allowed robots on your webpage, you will get crawled either way. Google recommends using sitemaps, however I don't think the bigger number of items in sitemap directly means better SEO. You might actually end up hurting your rankings, if you are feeding google low quality pages. In my SEO practice I actually exclude low quality items both from sitemap and indexing, but that is just me.

My personal recommendation is deleting every other sitemap besides the one generated by TSF, because if you have 404 pages they do not exist anyway. Watch those 404 links and 301 redirect them to existing relevant content or homepage to prevent hurting your rankings.

Lastly, you can read upon the issue, there is plenty of articles dealing with multiple sitemaps. Also you might want to ask this question on [moz forums](https://moz.com/), those guys are well equipped to answer general SEO questions, not only about wordpress. Hope it helps!

**Comment by sybrew** [comment]
To add onto LeBaux's reply:

Those extra items do not enhance SEO.
The sitemap is helpful for discovering items on your site, and to determine which have recently been updated.
After that is determined, the sitemap adds no value. It's not a ranking signal†, at all.

Also check out [this SEO tip](https://theseoframework.com/seo-tips/seo-tip-sitemaps-just-wait-and-see/).

_† aside from when the user is looking for super-recent and real news_

**Comment by epgunn** [comment]
Thanks to both of you!

Eileen P. Gunn
FamiliesGo!
www.familiesgotravel.com
#MOMtravelchat Twitter parties
Custom content outsourcing
familiesgo@gmail.com
917.533.2197
