### ISSUE TITLE
Setting description['social'] empties og & twitter tags, does not eliminate them

### ISSUE THREAD

**Issue by mikeselander** [sybrew/the-seo-framework#12]
Since there's currently no way to modify the description created in the plugin I'd like to stop the `og:description` and `twitter:description` tags from being created and run my own. However, when I turn social off using the `the_seo_framework_description_args` filter it only empties the meta tags and still displays them in the HTML.

Expected behavior would be for the tags to no longer exist in the HTML, allowing me to use my own.

Happy to create a patch and submit a PR if this is something you'd like to pursue 👍

**Comment by sybrew** [comment]
Hi Mike,

Sorry for the late reply, I forgot about GitHub issues :).

That filter is used for generation purposes, whether social is true or false determines how the description is being generated. Be it with or without additions, the length, etc.

What should be used is the filters that determine the Open Graph and Twitter descriptions.
The output of such (and its related filters) can be found within [/inc/classes/render.class.php](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/render.class.php).

If you wish to completely disable them, let me know and I shall add a "false" listener to it, rather than just "empty". This enhancement will then be added to the 2.7.0 update.

Thanks and have a great day! :)

**Comment by sybrew** [comment]
I'm going to refactor the render filters. Should be done in a few moments!

**Comment by sybrew** [comment]
See https://github.com/sybrew/the-seo-framework/commit/c8d1cafb89299599a4d215f6b7f76eaca5e3fff5

The description filters you're looking for are:
`the_seo_framework_description_output
the_seo_framework_ogdescription_output
the_seo_framework_twitterdescription_output`

Change the output to reflect what you need. If you return empty (false, '', null, 0, etc.) then the filter applied tags won't be output.

Due to be released with 2.7.0.

Enjoy!

**Comment by mikeselander** [comment]
Wonderful, thank you for the quick response Sybre! That's exactly what I was hoping for 👍
