### ISSUE TITLE
Twitter site/creator combination not being handled correctly

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#129]
I'm not sure the logic in `twitter_creator` is correct when the `twitter_site` option is set.

Steps to reproduce
1) Social Media Settings > Twitter, enter "@somesite' under your website's twitter profile. Personal profile is blank
2) Use the `the_seo_framework_twittercreator_output` filter to set an account for twitter creator, like "@myprofile". Or you could set the `twitter_creator` option in settings for Twitter personal profile.
3) Look at rendered output. It is showing `meta name="twitter:site:id"` because the `twitter_site` option was set above. It is not showing the `twitter:creator` meta, which is should be doing.

There are 4 Twitter card meta values. `twitter:site` and `twitter:creator` take the twitter handle string, and both can appear. As an alternative to either of these, you can use the numeric `twitter:site:id` or `twitter:creator:id` in their place, though this plugin doesn't seem to have the numeric IDs anywhere.

Right now, you are returning the `twitter:site:id` when the `twitter_site` option is set, and if it is not set, then returning the `twitter:creator` tag. When `twitter_site` is set, it is already returning the twitter handle string under `twitter:site`, so there is no need for `twitter:site:id` Also, you actually don't have the ID number anywhere to pull from.

**Comment by sybrew** [comment]
Related: https://github.com/sybrew/the-seo-framework/issues/61

If the "Your Personal Twitter Profile" option is left empty, it will fall back to "Your Website's Twitter Profile".
This is intended, as either the `twitter:site` or `twitter:site:id` meta tag is required. `twitter:creator` is not.

**However**, [this check is reversed](https://github.com/sybrew/the-seo-framework/blob/ff5e97ba5a319bb43ef613d9e9b33be92f9a4a7c/inc/classes/render.class.php#L536-L544)... 
**Plus**, you're correct about the numeric value. It should be `twitter:site` instead of `twitter:site:id`.

This output was introduced before the plugin was even named "The SEO Framework", and luckily you've found that was long overlooked. Thanks!

I'll see if I can make it more semantic and proper in the next update.

**Comment by sybrew** [comment]
Follow up: https://github.com/sybrew/the-seo-framework/issues/153

**Comment by sybrew** [comment]
> If the "Your Personal Twitter Profile" option is left empty, it will fall back to "Your Website's Twitter Profile".
This is intended, as either the twitter:site or twitter:site:id meta tag is required. twitter:creator is not.

This is no longer true. None of these tags are required anymore.
https://dev.twitter.com/cards/getting-started
