### ISSUE TITLE
"Add sitemap location in robots?" doesn't do anything

### ISSUE THREAD

**Issue by asgeo1** [sybrew/the-seo-framework#130]
The "Add sitemap location in robots?" option doesn't seem to do anything.

I think this is because the setting is named `sitemaps_robots`, but when you actually look in the code, the `can_do_sitemap_robots` function doesn't reference it at all. (although it does look for a setting called `sitemaps_output`).

**Comment by sybrew** [comment]
This was done because of if you were to use another plugin for the sitemap; it would be optional.
The plugin auto-determines the "best" scenario in many situations. Adding the location whilst knowing the sitemap is being outputted by the plugin itself locally implies that the addition in the robots.txt file should be present.

However, it does seem a bit confusing and it might annoy users who really want granular control.

Requesting feedback...

**Comment by asgeo1** [comment]
Thanks.  Well, I just wanted to turn off the "Sitemap:" bit in the robots.txt _temporarily_ for one of my sites.

I thought that's what the checkbox was for.  Yeah, is a bit confusing, because if the checkbox doesn't control that, it's not really clear what it does.

**Comment by sybrew** [comment]
You're right, it should be more binary. Users should be well aware of the options, especially since there's a link to the output.

Continued: https://github.com/sybrew/the-seo-framework/pull/131
