### ISSUE TITLE
Archive canonical should not be set on subpages when rel=prev & rel=next are present

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#132]
Go to page 2 or later of an archive page. Notice that there is a canoncial URL set for the paginated page, along with a `rel="prev"` and 'rel="next"` link point to previous and next pages in the series.

According to Google's documentation, this is an incorrect use of canonical URLs for paginated content.

https://webmasters.googleblog.com/2013/04/5-common-mistakes-with-relcanonical.html

Since prev & next links are present, the subpages of the paginated archives should not contain their own canonical URL.

**Comment by sybrew** [comment]
Hi @kevinlisota 

Could you quote the part that you are referring to?

Google suggest using a "view-all-pages-on-one-page" canonical URL. 
However, since WordPress doesn't offer that without heavily altering the query (that can break some sites), we refer to the current page. This isn't marked as a common mistake... 

See https://support.google.com/webmasters/answer/1663744 :
> For example, `http://www.example.com/article?story=abc&page=2&sessionid=123` may contain:
> ```
> <link rel="canonical" href="http://www.example.com/article?story=abc&page=2"/>
> <link rel="prev" href="http://www.example.com/article?story=abc&page=1&sessionid=123" />
> <link rel="next" href="http://www.example.com/article?story=abc&page=3&sessionid=123" />
> ```

**Comment by kevinlisota** [comment]
Hmm.. Maybe I was misreading. I guess it is OK, as long as the subpages do not have a canonical that points to the first page, which in this case it doesn't.
