### ISSUE TITLE
Selectively enable archive title prefixes with the_seo_framework_use_archive_title_prefix not working

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#137]
I am attempting to use the filter `the_seo_framework_use_archive_title_prefix` to selectively enable the archive title prefixes, but the logic on `use_archive_prefix` doesn't seem quite right.

In SEO settings, I have remove prefixes from title checked. So get_option('title_rem_prefixes') is true.

In my filter, I use some logic and say `if (is_date() ) return true;` My assumption would be that `use_archive_prefix` then becomes true.

However, the return takes the NOT of the option, which in my case would be false, and then combines it with AND from the filter, which is true. The result of evaluating `true && false` will return false, and that wasn't the intention here.

**Comment by sybrew** [comment]
Hi @kevinlisota 

> The result of evaluating `true && false` will return false, and that wasn't the intention here.

It is! 😄 I'll try to explain...

---

The function is a positive determination, i.e.:
`if use_archive_prexix() then $use_prefix is TRUE.`

When we look into `use_archive_prefix()`, the option to remove such is the opposite:
`if is_checked( 'title_rem_prefixes' ) then return FALSE. Thus use_archive_prefix() is FALSE. And $use_prefix is FALSE.`

To clarify: The option removes the prefixes. So, the option is a negative enabler.
That's why a NOT is used.

Simplified:
`( title_rem_prefixes == Title Remove Prefixes ) !== Use Title Prefixes`

---

The opposite is true for the filter:
`if filter use_archive_title_prefix is FALSE, then return FALSE.`
`if filter use_Archive_title_prefix is TRUE, then return TRUE.`

Simplified:
`( the_seo_framework_use_archive_title_prefix == Use Title Prefixes ) !== Title Remove Prefixes`

---

By default, the option is disabled. So the option will return false, so with NOT the function will return true.
