### ISSUE TITLE
strip html tags before outputting title

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#138]
It is possible, and sometimes useful, to insert HTML tags into WordPress titles. We use this to display some icon font characters on the front-end display to go along with our titles. Folks could also introduce html tags into a title that control styling for a portion of the title, say bold or italic.

The html tags are perfectly valid and sometimes quite useful for front-end display. However, they have no place in the `<title>` or other SEO meta tags hidden from the viewer. 

SEO Framework doesn't deal with this case. It does escape titles, which actually makes it worse by changing the html entities into displayable text, which then gets indexed by the search engines, when the only reason the html was there was for visual purposes.

I suggest introduce `wp_strip_all_tags` into your title generation to mitigate this case.

**Comment by sybrew** [comment]
I understand its usefulness to sometimes include it in the title (although it should be a theme option then).
However, we can't determine if it's intentional or not. In fact, themes should escape the title on output.

For example, we want this title:
`Why you should use <meta> tags.`

The theme must, for security reasons, convert it to this:
`Why you should use &lt;meta&gt; tags.`

I did an `intitle:"<meta>"` search and found this:
![image](https://cloud.githubusercontent.com/assets/7662236/26523382/c3059b54-4316-11e7-8f8c-618344f8ad67.png)

The SEO Framework goes one step further, by applying "prettifiers" on it.
https://developer.wordpress.org/reference/functions/wptexturize/

Implementation of such should also determine on-save whether the user has full HTML capabilities, or not. It should also determine whether it was intentional. And because we're going through a few loops of sanitizing the output, it will, in the end, be a race for security and expectancy without much benefit.

---

#### It has already been taken care of...
The reason I'm not going to consider this is mainly security. 

On top of that, you can manually insert a Custom Page Title in the provided SEO Meta box, for when you really want to use HTML tags in the title yet not display them as-is to the crawlers.

**Comment by kevinlisota** [comment]
We are converting from Yoast to your plugin, and Yoast actually does strip tags.

In our case, the html elements are on post_type_archive titles, which have no SEO Meta box, so the only way to address it is with your filters.

Actually, the biggest piece of feedback here is that you need a title/description settings page like Yoast that shows all post types, all archive types and allows templates for how the title and description should appear on each.

You have enough filters in place to do this sort of stuff in code, but the time I'm spending on it would got down to a few minutes if I could edit them all in one place in a template fashion.

I like the simplicity of your plugin compared to Yoast on many things, but in this case, that part of Yoast is superior.

**Comment by sybrew** [comment]
Hi @kevinlisota 

I understand that some plugins might fulfill the needs of particular installments better than others.

The way Yoast and AOISEO handle titles is in my opinion too verbose for TSF. The verbosity of such could vastly harm SEO when implemented wrongfully by the end-user, and therefore it will never be a default setting of TSF.

Nevertheless, it is possible to implement this with the provided filters, and it is in fact on my to-do list for an advanced, free extensions... somewhere.

I'll ask Siri to remind me opening an issue on this particular subject. I'll ping back here when it's published.

**Comment by GuardianMajor** [comment]
I have to agree with this, I just installed your plugin and so far loving it, very well done and clean. But the unexpected appearance of tags used for formatting titles for display showing up in the title are causing me issue.

I understand your position why by default you don't strip it but I think a better approach would be to strip HTML tags by default from page title and social shared titles or provide a global option to choose this behavior. And for those who want the actual tag to show up as part of the title, as you demonstrated technical articles might need that, then provide a checkbox for that post that says something like, display html tags in title so that post will have the tags show up as-is for purposes that are needed.

I believe that would be a better and more appropriate behavior in regards to tags in page and shared titles. So in summary:

- Strip tags in page titles and socially shared titles for the posts (aka Facebook) by default,
and provide post specific override of that behavior for those want to keep that on that post.
- Or, provide a global option that allows the user to choose to by default strip tags from titles (not post titles that are displayed on the site) for page titles and the titles shared on social. Alternatively, you can provide an inverse per post option that overrides that global strip on per post basis in case they ever need it.

All of this would be much like the options you provide for sitewide no index/follow/etc that are per post overridable. Thank you and hope you will consider and add this, currently it is preventing me from using this addon, which so far I like very much.

**Comment by sybrew** [comment]
@GuardianMajor I understand your concern, and the option to strip tags will be considered. Could you open a new issue for that? It may be short and sweet 😄 

Regarding the Google Plus tags, please see their documentation:
https://developers.google.com/+/web/snippet/

As you can see there, they use Microdata over Open Graph data. The theme can control microdata, but the Articles extension should also be able to influence it. The Articles extension, by default, doesn't use the custom title. If your theme outputs Microdata, and the tags are visible in Google Plus, then I can assume they escape whatever's in there outputted by the theme.

Articles will receive more updates in the future. So your suggestion will likely propagate towards it.

**Comment by GuardianMajor** [comment]
@sybrew Thank you, yes I will go ahead and open an issue for it.

As for the Google+ I am familiar with their tags and how it works, that's why I was surprised. I appreciate it and hopefully it will become more clear. what I know is that my theme doesn't output anything automatically.

I had been using a plugin that had worked solid for many years, it never had issues and the only reason I stopped was at the urging of the developer himself as he wasn't going to be working on it anymore and was worried changes would break it over time. I appreciated the heads up and did some research and chose this over Yoast and AIO Seo despite them having many features that this doesn't because I like the clean interface and feel it has potential in its simplicity. I just hope some much needed features are added at some point because right now it is not doing a few things, like sitewide metas involving authors/personas, ownership, language and keywords, etc.

Thanks again, appreciate the response.

**Comment by sybrew** [comment]
Hi @GuardianMajor,

I'm very open to feature suggestions. If you miss any feature that you adored in other plugins (or something new), feel free to open more issues 😄

To the few you've named:
- Keywords, [working on it](https://github.com/sybrew/the-seo-framework/issues/128#issuecomment-363299028)! The Dev version is already usable but misses features I want. 
- Authors/Personas: See the [Articles extension](https://theseoframework.com/extensions/articles/).
- Ownership: The Articles extension and Authorized Presence options in TSF utilize this.
- Language: This is handled by WordPress, TSF uses that information in its meta tags, and so should themes in the `<html lang="en-US">` tag.

If I missed any of those, or if you believe some are incomplete, as always: Feel free to open new issues 😄 

Cheers!

**Comment by GuardianMajor** [comment]
Thank you, I will happily do that for you. I am glad you have that in the works and I look forward to it when you feel it is ready.

I looked at the articles and I love all the features it has but to simply add the for example sameas meta, it seems a bit excessive but I will do more research on it when I get home.

**Comment by sybrew** [comment]
For the language `http-equiv` attribute:
- [Mozilla advises against content-language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Language#Examples).
- [WordPress states the language_attributes() tag should be used](https://codex.wordpress.org/Theme_Development#Document_Head_.28header.php.29).

I don't think TSF should implement the tag 😄

However, it is filterable, but it must be done at action `get_header`:
https://developer.wordpress.org/reference/functions/get_language_attributes/

Such an early call does add issues. So I'm deferring this for now.

**Comment by GuardianMajor** [comment]
Thank you, yes as I said already I am aware they discourage it but it has a specific use-cases where if you are generally say ENGLISH and you want to make a single post in FRENCH, then you can set the language settings for that post so that it knows it is different. I understand the extra work is not attractive, I can live without it, but suggested for sake of completeness for this great tool. Anyhow, hope you can come up with a better way down the line and consider it but in the meantime, I will defer to your decision on implementation. Thanks again for taking the time to discuss it with me. Appreciated. 👍

**Comment by sybrew** [comment]
Reconsidered via option rather as default, and provided a workaround: #270
