### ISSUE TITLE
More sitemap features

### ISSUE THREAD

**Issue by majiix** [sybrew/the-seo-framework#151]
Hi,
I think sitemap features can be a lot more. like:

1. Excluding CPTs and taxonomies
2. Excluding pages like authors or archives
3. Setting up priorities 
4. A check box in add new post that adds or removes post or page from site map
5. Compressed sitemap

and many more that i can't remember right now.

**Comment by sybrew** [comment]
Hi @majiix 

Thanks for the suggestions! I'd like to walk through them.

First and foremost, I'd like to remind you that the sitemap is for Search Engine consumption. Adjusting anything within is most likely redundant. 

Reducing within from what's otherwise publicly accessible is in the simplest sense useless.
In a more rigorous way, the sitemap shouldn't be relied upon. It is not a ranking factor in any way; other than having new or otherwise adjusted posts found more easily.

With all that in mind:

1. Why? Nevertheless, this can already be achieved through two filters: [this one specifically](https://github.com/sybrew/the-seo-framework/blob/b2c7b3462380b6b3128f9b5324d988dc6e88a139/inc/classes/sitemaps.class.php#L876).
2. Archival pages aren't included already.
3. This is handled automatically and will cause overhead. Aside from that, it doesn't help changing the values.
4. There already is: "noindex".
5. The sitemap is already quite compressed. It's not outputting spaces, but tabs, for instance. Compressing it will require checks for each of these outputs, which will actually make it much less efficient. In any case, it won't be future proof; I want to implement PHP 5.5 generators on it when the time comes, that will rewrite the output structure.

Keep in mind: The more features we add, the more issues we bring to the table.
Also, the bigger the project, the more time it will consume. And I can't afford time for something that's actually overlooked by Search Engines anyway.

**Comment by majiix** [comment]
OK, I'm convinced. Really.
Just for confirmation, author pages are excluded, right?

**Comment by sybrew** [comment]
😅 

Yes, author pages are excluded.

I'm leaving this open for awhile to see if anyone wants to provide more feedback.

**Comment by cabatint** [comment]
+1 on being able to set certain (custom) taxonomies and CPTs to be excluded from sitemaps, because they can be "helper" items that are not meant to be displayed on their own. For example I'm setting up a calendar and using taxonomies to connect the displaying events (separate CPT) to the owning CPT. In this particular case, I don't need to display the events individually. I'll just roll them up to the parent - and I'm using a connecting taxonomy to create the relationship (which I don't need indexed either). There may be a better way to setup this infrastructure, but  it's helping with keeping everything straight for the moment. I'd prefer not to go through filters so for now I'm just "no indexing" on item by item.

**Comment by sybrew** [comment]
@cabatint 
> There may be a better way to setup this infrastructure...
You're doing fine. 😃 

However, those CPT entries shouldn't be annotated as public when they shouldn't be reached, or when they only function as helper items.
When a CPT isn't public, it won't be added to the sitemap.

Also, when the CPT shouldn't be publicly queryable, the `rewrite` argument should be `false`. 
This will prevent it from being added to the sitemap.

For more information, visit:
https://developer.wordpress.org/reference/functions/register_post_type/#parameters

If you didn't add the CPT yourself, you can filter it using filter `register_post_type_args`. With that, you can adjust those mentioned arguments.
https://developer.wordpress.org/reference/classes/wp_post_type/set_props/

**Comment by cabatint** [comment]
Thanks! I'll have to check out those ideas to see if configs result in the behavior I'm looking for. For the most part I'm building on the fly with mostly default settings into a custom plugin & theme. (I'm using the Genesis framework in combination)

It's not the end of the world is person gets to the CPT page, I'd just prefer it not create noise in the crawled SERPs (at least for this iteration). I don't see these "helpers" too much differently "attachments" for example. The archive-level is available/linked for both CPTs I'm currently working with.

If you're building something outside of a typical blog, more of a data/content site, these other types of infrastructure pages may become more useful as pages in their own standing. On my other project CPT archives and individual custom taxonomy pages have been my highest used pages. 

I'm surprised that CPT archives aren't a configurable include/exclude. I was expecting to see them in the sitemap. And same for the custom taxonomy pages that I need crawled and linking to directly, I'm not seeing those in the sitemap. In the main SEO settings I have tags and categories as allowed.

**Comment by sybrew** [comment]
https://theseoframework.com/seo-tips/navigation-and-naming-internal-links/
> Do not depend on your sitemap too much, if a user can’t find a page, then why should a Search Engine?

This is where breadcrumbs and other structural improvements comes into play.
For example, if you take the linked SEO Tip page, you'll see it linked to three times above the fold.
Genesis does support all of this, so you're covered 😄.

![image](https://user-images.githubusercontent.com/7662236/27778080-6a99506e-5fb8-11e7-8681-cde16b052170.png)

**That said...**
If implementation was easy, I'd do it. But there are too many factors most programmers don't consider... Like propagated/bubbling cache busting, correctly pinging on change events, listening to amount of items in the archive, etc.

Also, once I implement support, I need to maintain it. A simple addition might result in at least ten times its initial effort. I can't afford 7500 to 15000 USD for something essentially disregarded.

On top of that, I'd much rather set up other improvements, like [all what's planned for 3.0.0](https://github.com/sybrew/the-seo-framework/issues?utf8=%E2%9C%93&q=is%3Aissue%20milestone%3A3.0.0%20), whereof some are related to archives.

So, I'd rather leave Search Engines to discover the categories and tags through regular crawling rather than through the sitemap.

**Comment by cabatint** [comment]
Hi. 

Thanks and I completely understand the having to figure out what's in the budget and prioritizing according. And that some things that seem like they should be easy aren't. I'm testing out your plugin on a new site to see if it's a fit ("kicking the tires"), or for which types of sites it fits well for, etc etc. Great work on bringing the plugin to it's current state. 

I agree that it's best for search engines to find the pages, but I'm also looking for ways to indicate which pages have been updated. The pages themselves are pretty well linked (at least in the examples I'm working with). When the site gets above 1,000 pages the impact of the crawler gets a bit intense if I don't have some way to indicate what's changed, what's new, etc.

**Comment by sybrew** [comment]
Hi @cabatint 

When your site's getting huge, the indexing performance will then depend more on its [crawling budget](https://webmasters.googleblog.com/2017/01/what-crawl-budget-means-for-googlebot.html).

Google tries to identify when content is updated, automatically. 
I quote (from the crawling budget link):
 
> Staleness: our systems attempt to prevent URLs from becoming stale in the index.

This is also very important, which supports my earlier statements:
> Q: Is crawling a ranking factor?
> A: An increased crawl rate will not necessarily lead to better positions in Search results. Google uses hundreds of signals to rank the results, and while crawling is necessary for being in the results, it's not a ranking signal.

In the end you should focus on content quality, website usability, and marketing overall. 
Technical factors will easily fall short when comparing them to human emotions.

**Comment by cabatint** [comment]
Hi @sybrew,

Thanks. For sure. I've been at this for a while and I know there's always more to learn. My other project is pushing about 30K page views for month across 1,000+ pages, ironically in the UX space.  I'm testing out you SEO plugin as an alternative for a new project and one can always hope to have similar results on a new project. I'm also using my past experience with site building/growth to see how things line up. I'm more of a UX designer that dabbles in technology building from time to time :)

**Comment by sybrew** [comment]
Closing thread. Continue on #31.
