### ISSUE TITLE
Generate wrong url when install WP in subfolder

### ISSUE THREAD

**Issue by nhymxu** [sybrew/the-seo-framework#16]
I install WP on subfolder /blog/
http://abc.com/blog/
But some meta url wrong

`<meta property="og:url" content="http://abc.com/category/linux/" />`
`<link rel="canonical" href="http://abc.com/category/linux/" />`

Right url is 
`<meta property="og:url" content="http://abc.com/blog/category/linux/" />
<link rel="canonical" href="http://abc.com/blog/category/linux/" />`

**Comment by sybrew** [comment]
Hi Dũng Nguyễn,

Is this happening on only the blog entries as categories, or as well as the singular post types (post/page)?

The pull request only features a change in the archive path, and I believe this should be handled elsewhere. 
But if it's only faulty on archives, then I believe we are facing another issue. I also see you're using `site_url()` rather than `home_url()`, so I really need more information on this matter.

I also believe the change should be added here:
https://github.com/sybrew/the-seo-framework/blob/537a5638fa363a3e2dd5e6227073fec6fb20cbb9/inc/classes/generate-url.class.php#L1373-L1375

Do keep me informed. Thanks!

**Comment by sybrew** [comment]
See patch: https://github.com/sybrew/the-seo-framework/commit/936db0785e322a585d607cc7b989f2de2ebcd03f

Specifically these lines: https://github.com/sybrew/the-seo-framework/blob/936db0785e322a585d607cc7b989f2de2ebcd03f/inc/classes/generate-url.class.php#L740-L742

```
//* Add plausible domain subdirectories.
$url = trailingslashit( get_option( 'home' ) ) . ltrim( $path, ' \\/' );
$path = $this->set_url_scheme( $url, 'relative' );
```

It's untested, but should yield what you're aiming for. Feel free to test it out. This makes all path generation functions yield the same results.

Caution: please note that the 2.7.0 version (currently in Alpha) transfers term data to the WordPress 4.4 system. This needs more elaborate testing prior to be used on production websites.

**Comment by nhymxu** [comment]
I see Google Webmaster notice with /category/ and /tag/
post/page work well.
