### ISSUE TITLE
strip html tags before outputting meta description

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#163]
When generating a meta description from excerpts, this plugin should strip all HTML tags before outputting the meta description. This accomplishes two things.

1. Search engines do not use HTML formatting when showing meta descriptions in search results
2. This impacts the maximum character counts for meta description text, as html tags can take up lots of space.

An easy way to replicate this is to enter an author description under biographical info in their profile like this:

`<strong>This is a WordPress author bio</strong>`

Notice that it outputs the HTML tags into the meta and og description fields and prematurely truncates the description text.

**Comment by sybrew** [comment]
Hi @kevinlisota,

This is intentional. It's converted to be as displayed, but it's not HTML rendered.
In fact, it's the shortcoming of theme authors to escape the input.

i.e. `<span>` should become `&lt;span&gt;`.

You can view a perfect example in the image below.

![image](https://user-images.githubusercontent.com/7662236/27388027-91f8b19e-569a-11e7-9250-00f7c26ce0f0.png)

I understand that's it might be annoying and that you can use those entries for markup, but unless WordPress supplies a TinyMCE (or its future version thereof) on those fields, I see no reason to strip those tags.

For this, you can add a custom description and title.
I know, it's not available yet for authors. However, it's planned: https://github.com/sybrew/the-seo-framework/issues/61

**Comment by sybrew** [comment]
I forgot to mention, for the "premature truncation"... you're right.
That is covered in this issue, where we should render HTML entities too: https://github.com/sybrew/the-seo-framework/issues/161

**Comment by hadingrh** [comment]
My author page archieve's title meta also doesn't output correctly. 
i,e  Articles by &lt;span class="vcard"&gt;Hadi Nugraha&lt;/span&gt;

**Comment by sybrew** [comment]
@hadingrh 
Wouldn't your theme be better if it used `body.author h1`, rather than injecting it through text fields for `span.vcard`?

Once more:
> It's a shortcoming of theme authors not to escape the input.

**Comment by hadingrh** [comment]
Indeed. Thanks for a simple solution. 
How can I missed that.
