### ISSUE TITLE
Strip oembeds from description

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#164]
oEmbed URLs should be stripped out of meta descriptions.

Steps to replicate:

1) Enter a post. Make the first line of text an oEmbed, like a YouTube URL or similar, followed by more text.
2) Do not enter an excerpt (let the plugin auto generate the description)
3) Notice that the meta and og descriptions have the oEmbed URL in them, which obviously doesn't make sense.

The plugin should be aware of all registered oEmbeds and strip those out during auto-generation of the description field.

**Comment by sybrew** [comment]
Thanks Kevin! Well spotted 😄

I'm unsure if this enhancement will be feasible, as the text is fetched as-is and oEmbed seems to determine implementation on-the-fly through JavaScript.

**Comment by sybrew** [comment]
3.2 will be focussed around the description rewrite. Let's get 3.1 out first.

**Comment by sybrew** [comment]
Initial write of the function:
```php
function strip_embeds( $content ) {
	global $wp_embed;

	if ( $wp_embed instanceof \WP_Embed ) {
		$embedded = $wp_embed->autoembed( $content );
		// Do stuff with it...
	}

	return $content;
}
```

It's difficult to discover what's inserted as an embed.  WordPress doesn't provide an array of links that are converted to embeds.
There are filters available, in which we can nullify the content. However, this will be JIT behavior.

I think it's best to strip all URLs that are placed on new lines, instead of hijacking embed functionality.
