### ISSUE TITLE
Custom fields. Retrieve all SEO data by post ID

### ISSUE THREAD

**Issue by ruskid** [sybrew/the-seo-framework#169]
Hello, couldn't find any specific information.

I am working with xmlrpc, when I query get_posts, I also need to get all related SEO information of the post.

For now I can only think about:
```
 'title' => the_seo_framework_title_from_cache(),
 'description' => the_seo_framework_description_from_cache(),
```

In Yoast you got this information in custom fields. How to query this information?

Thanks for the plugin.

**Comment by sybrew** [comment]
Hi @ruskid 

You can fetch any post metadata through [get_post_meta()](https://developer.wordpress.org/reference/functions/get_post_meta/). Just like Yoast SEO.

These are the data keys, with their default value attached:
```
[
	'_genesis_title'         => '',
	'_genesis_description'   => '',
	'_genesis_canonical_uri' => '',
	'redirect'               => '',
	'_social_image_url'      => '',
	'_social_image_id'       => 0,
	'_genesis_noindex'       => 0,
	'_genesis_nofollow'      => 0,
	'_genesis_noarchive'     => 0,
	'exclude_local_search'   => 0,
	'exclude_from_archive'   => 0,
]
```

```
//Example:
$custom_title = get_post_meta( $post_id, '_genesis_title', true );
```

If you wish to get rendered output, you should check out the [Render class](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/render.class.php). Within that class, all kinds of fetching data are used.

The cached methods can be found [here](https://github.com/sybrew/the-seo-framework/blob/2a05d8f846025987a5f9326a1d66e98133dd38ff/inc/classes/render.class.php#L51-L199). I highly suggest using the object-oriented style instead of the procedural style. It gives you much more control.
They should be called like this, when public:
```
// Get object.
$tsf = function_exists( 'the_seo_framework' ) ? the_seo_framework() : null;

if ( isset( $tsf ) ) {
	// code here...
	
	// Example:
	$twitter_card_type = $tsf->get_current_twitter_card_type();
	$description = $tsf->description_from_cache( $social = false );
}
```

If you're new to object-oriented programming, try the example above and give yourself room for trial-and-error 😄.

Let me know if you have any more questions. Cheers!

**Comment by ruskid** [comment]
Thanks a lot! 
Yep I got it mixed, cause only not every info is queried from cache =)
```
$tsf = function_exists('the_seo_framework') ? the_seo_framework() : null;
        $seo = [];
        if($tsf) {
            $seo['title'] = $tsf->title_from_cache();
            $seo['description'] = $tsf->description_from_cache();
            $seo['social_image'] = $tsf->get_image_from_cache();
            $seo['ld_json'] = $tsf->ld_json();
            $seo['redirect'] = get_post_meta( $entry->ID, 'redirect', true );
            $seo['canonical'] = get_post_meta( $entry->ID, '_genesis_canonical_uri', true );
            $seo['noindex'] = get_post_meta( $entry->ID, '_genesis_noindex', true );
            $seo['nofollow'] = get_post_meta( $entry->ID, '_genesis_nofollow', true );
            $seo['noarchive'] = get_post_meta( $entry->ID, '_genesis_noarchive', true );
        }
```

**Comment by sybrew** [comment]
No problem :) The code looks good! 

For what it's worth, function `get_post_meta()` caches the post metadata 😄.

If you wish to follow-up, feel free to re-open this issue. Have a great weekend!
