### ISSUE TITLE
Issue with build_title_doingitwrong method

### ISSUE THREAD

**Issue by fprezat** [sybrew/the-seo-framework#170]
Hello sybrew,

I'm working with your plugin and i have an issue with the `build_title_doingitwrong` method in the `Generate_Title` class in `generate-title.class.php` file.

When building the title within this method, you fetch the blog name like so `$blogname = $this->get_blogname();` but you do not use it anywhere... 

So the resulting title looks like "My awesome title -" instead of "My awesome title - my awesome blogname" (please check the screenshot attached).

Can you check this method please ?
Thank you.

![seo-framework-title-issue](https://user-images.githubusercontent.com/14160261/27950033-18026908-6300-11e7-98ef-5bac56a54c57.png)

**Comment by sybrew** [comment]
Hi @fprezat 

The method name states that it's doing it wrong 😅. It's wrong because the blog name and other stuff have been added beforehand. The useless `$this->get_blogname()` call is a leftover from moving methods around for semantics, you can ignore it.

The method is there to solve most common issues that theme authors bring to the table. Alas, it can't catch everything because `wp_title()` is inherently broken.

#### Solution 1 (Additional plugin)
If you're experiencing title output issues, you might find it useful to use the Title Fix extension, brought with the [Extension Manager](https://wordpress.org/plugins/the-seo-framework-extension-manager/).
Alternatively, if your server doesn't support PHP5.5+, the old [Title Fix](https://wordpress.org/plugins/the-seo-framework-title-fix/) plugin should work well too.

#### Solution 2 (Theme code adjustments)
See this post: https://wordpress.org/support/topic/duplicate-title-still-active/#post-7576845
I suggest using Method 2.

>If you wish to have a more future-proof (and faster!) title output, pick this method.
> You’ll need to remove the title output completely (in `header.php`), and add the following to your `functions.php` file:
>
> `add_theme_support( 'title-tag' );`

**Comment by fprezat** [comment]
Arf, i saw the `title-tag` in your code but i went too quickly on it ;)
It works adding the theme support.

Thank you
