### ISSUE TITLE
Use post_link filter instead of template_redirect

### ISSUE THREAD

**Issue by andremacola** [sybrew/the-seo-framework#172]
It is better to use **post_link** filter ( https://codex.wordpress.org/Plugin_API/Filter_Reference/post_link ) as option for redirect posts, with post_link the permalink structure and functions will return the final link and not the post permalink. With some cache options, post link can be a problem and I think it is not the best SEO solution.

**Comment by sybrew** [comment]
There's a big difference between a hook and a filter.

A filter adjusts the code.
A hook fires code.

We need to fire a redirect, not change WordPress' code output. 
That's where the top-of-the-page link is for.

Nevertheless, I traced the `post_link` filter, and it doesn't seem to influence rewrite rules. Could you verify this?

About the SEO part, when the page accessed returns 301, anyone should*/will follow that link. Its link juice will propagate correctly. There's no harm here.

*It can be ignored. That's why we always need to use `exit;` afterward, so the listener will only get the `HEAD`.
