### ISSUE TITLE
Allow Exceptions to Global Noindexing

### ISSUE THREAD

**Issue by nateonawalk** [sybrew/the-seo-framework#174]
The ability to create <noindex> exceptions for individual URL paths would be so incredibly helpful to those of us trying to complete a content audit.

There are lots of SEO plugins I've found (like TSF) that allow for 'noindex all tag/category/post pages.' There are **no** SEO plugins I've found that allow for 'noindex all tag/category/post pages _EXCEPT_:

/tags/my-tag-that-gets-good-traffic/
/my-category-that-has-backlinks/

etc.'

Would this be possible? Perhaps in the form of a field box underneath the noindex check-boxes in the user admin that takes one argument on each line? And is there any way to manually do this in the meantime? I have a site with around 6k tags that I'd like to noindex... except about 80 of them.

Thank you~

**Comment by sybrew** [comment]
I can't find my original comments on this, but the gist is:
If we enable something on X, then something's disabled on Y, and vice versa, users get very confused. Myself included as whom created the core.

In conclusion, reverse options are very tricky to conceive and include.
What would be much better is adding a bulk-editor.

In the meantime, there's no good filter available.
The one from [get_metadata()](https://developer.wordpress.org/reference/functions/get_metadata/) prevents fetching of other data. 
The one from [the_seo_framework()->get_term_meta()](https://developer.wordpress.org/reference/functions/get_metadata/) won't run after you've ever saved the term metadata for the term.

That said, the latter is good for setting the defaults. And, if you haven't saved the term since you've installed TSF, it will work.
```
add_filter( 'the_seo_framework_get_term_meta', function( $data = array(), $term_id ) {

	// Set your exclusion ids.
	$exc_ids = array( 1, 2, 3, 4, 5 );

	if ( in_array( $term_id, $exc_ids, true ) )
		return $data;

	$data['noindex'] = 1;

	return $data;
}, 10, 2 );
```

Now, I haven't tested the above filter. But it should affect The SEO Bar, so you can easily see if it works.
