### ISSUE TITLE
HTML in Archive titles

### ISSUE THREAD

**Issue by BinaryMoon** [sybrew/the-seo-framework#183]
In my theme I am using a filter to add some html to my archive titles to wrap the prefix in a span. This allows me to style, or even hide, the prefix. If I enable the prefix in archive titles then the html is displayed as well. It's escaped but I think it should be removed since it's not relevant.

You can see how I am wrapping the prefix here:
https://github.com/BinaryMoon/granule/blob/f3552634ba799dbbb9b526cd9da70657b70171bd/inc/wordpress.php#L603-L639

And here's what it looks like when output:
<img width="706" alt="screen shot 2017-08-26 at 11 56 20" src="https://user-images.githubusercontent.com/1004130/29740754-b1f19bb6-8a55-11e7-8c0c-a5fc8c155680.png">

I can't think of a situation where you would want html in a page titles, so I would stop escaping html, and instead remove it entirely.

At the moment I have hidden the prefix - but it would be nice to be able to add it back if I can :)

**Comment by sybrew** [comment]
Hi @BinaryMoon 

The theme should take care of what the users see. The WordPress interface should project input information to the theme.

Now, we're dealing with two things, regarding the same input:
1. Visible HTML output.
2. SEO meta output.

In a perfect world, the theme should do exactly the same as TSF does, namely escaping or at least sanitizing the output and show it as-is. 
This means no HTML manipulation should be possible through default input. i.e. Naturally steering users away from such practices.

So, all themes should output them as-is. And therefore, with the aforementioned limitations regarding sanitation, we shouldn't insert HTML in the title.

I hope this helps you understand that these adjustments should actually be taken from a different angle.

Nevertheless, adjusting costs a lot of time, so we'll continue with what we have 😄. 
Now, I see you'd love to automate things. 

The quick and dirty solution is to pass another `wp_kses()` or even `esc_html()` onto the SEO output. In this example, I'm using `esc_html()`. Because the separator can also be HTML encoded, I'm unsure if `esc_html` is the right choice. However, you can always fall back to `wp_kses`:
```php
add_filter( 'the_seo_framework_pro_add_title', function( $title, $args, $seplocation ) {
	return esc_html( $title );
}, 10, 3 );
```

Within that filter, you can also add conditionals when required. The wished-for title should always be returned.

Note, that aside from that filter, TSF also has a manual SEO title input field. Which could also alleviate this issue without adding the filter above. But, your theme adjustments also targets archives that TSF can't touch throughout user input. So the filter above, in your case, would be the best solution.

**Comment by BinaryMoon** [comment]
Hi - thanks for the reply. Unfortunately I'm not sure I understand your reasoning here. The theme does not accept any non default user input and filters the title tags. Everything is sanitized.

The code I am applying is not dissimilar to code that is being considered for core:
https://core.trac.wordpress.org/ticket/38545#comment:19

This adds spans around the prefix for the same reason I am adding them. To allow users to hide the prefix/ themers to style the prefix. Here's an example of one of my premium themes on wordpress.com that has a styled prefix:
https://carmackdemo.wordpress.com/category/artwork/

Thanks for the tip on the filter. That's what I needed - I used strip_tags to remove the html.
```
function bm_the_seo_framework_pro_add_title( $title ) {
	return strip_tags( $title );
}

add_filter( 'the_seo_framework_pro_add_title', 'bm_the_seo_framework_pro_add_title' );
```

I still think that this should be part of the plugin rather than something I add via another plugin. I'm able to make these changes but:

1. There may be html added to the title in the future via core
2. Other plugins/ themes may do something similar and not have the knowledge or expectation that the prefix could be used in this way.

**Comment by sybrew** [comment]
What I tried to convey is that WordPress doesn't separate `<title>` tag titles from `<h1>` tag titles within their functions.
This means that the titles can be used either way and therefore HTML should never be passed into the filters or fields.

For themes, I believe the output should be manipulated in-line, rather than through filters.

For this, many "echo" functions are there, i.e. without "get", like `the_archive_title()`. 
Alternatively, you can use `single_term_title()`, through which you can pass a conditional prefix as you desire.

With that, and without the use of core filters, you're exempted from both plugin-and user manipulation. Which, in the long run, will save you a lot of time.

So, passing arguments instead of filters is essentially the way to go 😄

**Comment by BinaryMoon** [comment]
Ah ok - I understand what you mean now. Thanks for clarifying.
