### ISSUE TITLE
New filter for CPT to support Breadcrumb schema

### ISSUE THREAD

**Issue by jackgregory** [sybrew/the-seo-framework#209]
Before #146 is implemented can a new filter be added to `generate-ldjson.class.php` line [419](https://github.com/sybrew/the-seo-framework/blob/2.9.4/inc/classes/generate-ldjson.class.php#L419)? Allowing custom taxonomy to be returned.

e.g. `apply_filters( 'the_seo_framework_ld_json_breadcrumb_taxonomy', $cat_type, $post_id );`

This way plugins or themes can add breadcrumb schema to cpt with custom tax.

**Comment by sybrew** [comment]
Good idea!

Note that the breadcrumbs will be rewritten for 3.0.0. See #32. 
We're going back to a single trail, rather than multiple, and only support the primary category (which will be alphabetically auto-selected if not set).

Note that when #146 is implemented, this filter shouldn't be necessary, but it can then be used to exclude some.
So, we'll look into #146 beforehand, and I'll feed back on this issue as we progress.

**Comment by sybrew** [comment]
The filter will be `the_seo_framework_ld_json_breadcrumb_taxonomies`, but I don't think it'll be necessary as #146 is done.

```php
/**
 * Applies filters 'the_seo_framework_ld_json_breadcrumb_terms'
 *
 * @since 3.0.0
 * @param array|string  $taxonomies The assigned hierarchical taxonomies.
 * @param string        $post_type  The current post type.
 * @param int           $post_id    The current Post ID.
 */
$taxonomies = \apply_filters( 'the_seo_framework_ld_json_breadcrumb_taxonomies', $taxonomies, $post_type, $post_id );

// The first will be used:
if ( is_array( $taxonomies ) ) {
	$taxonomy = reset( $taxonomies );
} else {
	$taxonomy = $taxonomies;
}
```
