### ISSUE TITLE
Schema.org Articles script output (+AMP)

### ISSUE THREAD

**Issue by peiche** [sybrew/the-seo-framework#21]
If there is a featured image on a post or page, shouldn't the json-ld generated markup create an "image" entry?

**Comment by sybrew** [comment]
Hi peiche,

Do you mean the [Schema Articles](https://developers.google.com/search/docs/data-types/articles) markup?

All those are planned to some extend for the SEO Framework.

When they can't be automated, like the [Social Profile Links](https://developers.google.com/search/docs/data-types/social-profile-links) (formerly known as the Knowledge Graph), or are much too advanced for the general user, they'll likely become extensions.

The Schema Articles are planned for 2.8.0, all data is already readily available so it shouldn't be a problem implementing this :smile:. 
If you mean this, please state so because I can then mark this topic with several labels and a milestone.

Thanks!

**Comment by peiche** [comment]
Yes, I do mean the Schema Articles markup.

**Comment by sybrew** [comment]
It's a bit too complex at the moment to get it right whilst abiding to Google Webmaster guidelines and overseeing the scale of the 2.8.0 update as it already is.

Google also recently updated the markup, where they recommend using it in combination with AMP, as they allow much more info there.

I think it's best to focus on what we already have and improve that before adding even more features.

Moved to 2.9.0 or even an extension that will cover the lot, including AMP.

**Comment by sybrew** [comment]
Based on [these guidelines](https://developers.google.com/search/docs/data-types/articles#article_types), Google's [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) is **marking errors incorrectly** and assumes input to always be the AMP-version.

Unfortunately, I'm postponing this project while seeing how Google develops and will be live testing this on https://theseoframework.com/. I also sent Google feedback, and looking at how active they are: this should be working correctly soon 😄.

**Comment by ladislavsulc** [comment]
Looking forward for AMP support! Thank you.

**Comment by sybrew** [comment]
**Good news:** Google Webmasters doesn't mark the data as incorrect.

**Comment by sybrew** [comment]
@ladislavsulc AMP support should be released this weekend (or somewhere next week) as a free extension! 🎈 

[View the files here](https://github.com/sybrew/The-SEO-Framework-Extension-Manager/tree/master/extensions/free/amp/trunk).

Please note it's currently not 100% compatible with the [AMP for WP](https://wordpress.org/plugins/accelerated-mobile-pages/) add-on for the original [AMP plugin](https://wordpress.org/plugins/amp/). 
What this means is this: it causes an inconsistent admin experience... luckily: that's all.
In most circumstances, everything should work; but, the specifics (i.e. removing their SEO settings and replacing it with our own) should still be worked out.

So, for now: it's completely automated 😄

**Comment by ladislavsulc** [comment]
@sybrew You're the best!

**Comment by sybrew** [comment]
Both extensions have just been released:
https://wordpress.org/plugins/the-seo-framework-extension-manager/changelog/

The AMP extension is free.

The Articles extension is temporarily premium, until γ-test is done. Google has just started implementing and improving this; therefore, the output is still marked invalid. 
I also do not want to receive hundreds of 1-star ratings because the output is marked invalid (although it's valid). Google is shifting fast, and I'll do my best to keep up 😄 

Enjoy!
