### ISSUE TITLE
Post SEO Settings -> Custom Social Image URL

### ISSUE THREAD

**Issue by TBLim** [sybrew/the-seo-framework#234]
Hi,
When I clicked on Select Image and choose a image from Media Library, and clicked on Insert into Post, a blank screen resulted instead of inserting the File URL into the original entry box.
Am I selecting the image under Open Graph correctly? Tq!

**Comment by sybrew** [comment]
Hi @TBLim 

Could you enable [WP_DEBUG](https://codex.wordpress.org/WP_DEBUG) and see if an error pops up?
If so, could you share that error?

Thanks!

**Comment by TBLim** [comment]
Hi,
I turned on WP_DEBUG via Debug plugin (https://wordpress.org/plugins/debug/) and received the attached error email.

[Error Reporting from <b>Ministry of Body 身 . Mind 心 . Spirit 灵<:b> with the help of <a href="http:www.soninow.com" target=_blank">www.soninow.com<:a>.pdf](https://github.com/sybrew/the-seo-framework/files/1548780/Error.Reporting.from.b.Ministry.of.Body.Mind.Spirit.b.with.the.help.of.a.href.http.www.soninow.com.target._blank.www.soninow.com.a.pdf)

![screenshot-tblim ql sg-2017-12-12-01-22-20](https://user-images.githubusercontent.com/18502758/33844625-ca0a2116-dedb-11e7-9933-593489a92868.png)
<img width="1440" alt="screenshot 2017-12-12 01 24 14" src="https://user-images.githubusercontent.com/18502758/33844645-d6781930-dedb-11e7-8b45-f794b74bf0b7.png">

**Comment by sybrew** [comment]
Hi @TBLim 

Thanks for sharing the details!

Unfortunately, the error in the PDF file you've shared isn't the cause of the issue. Because, it shouldn't cause a white screen, as it won't stop script execution.

#### Example:
```php
<?php

$thing = 0; // int
$thing->non_existent; // Line number 4: access property as object

echo 'testing testing';

//= output:
// NOTICE Trying to get property of non-object on line number 4
// testing testing
```

*Pings Flowplayer's author regarding the reported notice*: @fvmartin.

#### Diving deeper

If you're not receiving any other error messages, it might be that a plugin or theme injects extra code that your browser can't resolve. But, before we dive any deeper into that, I await your response regarding any **Parse, User or Fatal Errors** you might've received.
