### ISSUE TITLE
CPTs not displaying in sitemap.xml

### ISSUE THREAD

**Issue by wassim** [sybrew/the-seo-framework#248]
My public CPT entries are not displaying in the generated sitemap. I deactivated the sitemap generation cache and updated my CPTs but still nothing. Normal WP posts are in the sitemap.

Am I missing something here? Is there an extra setup to make this work?

**Comment by sybrew** [comment]
Hi @wassim, 

Happy New Year!

The post type must support the `title` and `editor` attributes.
With that, it must also have `rewrite` enabled and be `public`.

**Comment by wassim** [comment]
@sybrew Added `editor` attribute to supports. Now it works! Thanks.

May the new year bring success to you and to TSF!

**Comment by timalbert** [comment]
Is there any reason why `editor` would need to be a required attribute? We have a CPT that does not use it, but would like the entries to be included in the sitemap.

**Comment by sybrew** [comment]
@timalbert Since 3.0.4 that's [no longer required](https://theseoframework.com/?p=2264#detailed).

> The SEO settings now show up on every publicly queryable post type. Title and editor fields are no longer required.

Instead, the post type have these values set to `true`:
1. `public`
2. `rewrite` (or `_builtin`)

Keep in mind that the sitemap maintains a cache. You can flush the cache by re-saving the SEO settings.

**Comment by timalbert** [comment]
@sybrew Yikes where have I been - I am on 2.6! Thanks for the pointer!!
