### ISSUE TITLE
Force Schema Breadcrumbs on Pages

### ISSUE THREAD

**Issue by KimchaC** [sybrew/the-seo-framework#254]
Hi,

It seems like schema breadcrumbs are only created for blog posts, but not for pages.Here are some examples:

https://theseoframework.com/about/tsf-3-0-beta/

The blog post has breadcrumb schema data.

https://theseoframework.com/contact/

This page does not.

And it is reflected in the google results:
https://www.google.com/search?q=site%3Atheseoframework.com

Thanks for looking into this and for creating this great plugin!

**Comment by sybrew** [comment]
Hi @KimchaC,

The page isn't hierarchical. If I'd set the "parent" attribute for the page, then breadcrumbs will arise.
![image](https://user-images.githubusercontent.com/7662236/34997224-2e2baa0e-fadc-11e7-992c-0008b239091d.png)

Nevertheless, I think adding breadcrumbs towards the homepage might a great addition regardless of its state. But I'm a bit hesitant on this because it can "subjectively taint" the results greatly.

If I'd implement it as you suggest, then the output will be like so:
![image](https://user-images.githubusercontent.com/7662236/34997407-bcc1f2f0-fadc-11e7-83b2-51d3a0de5e34.png)

**Comment by KimchaC** [comment]
Yeah, this is what I would expect it to look like. Am I wrong in my assumption that the only benefit of the breadcrumbs is that they make the content standout and look more userfriendly?

Wouldn't that benefit pages too?

**Comment by sybrew** [comment]
Nope, you're right in your assumption. I believe it's better, too.
However, I don't think everyone will welcome such change.

Therefore, I'm waiting for feedback from other users, too.

**Comment by KimchaC** [comment]
Perhaps this could be a separate checkbox that wouldn't be checked for people who update by default?

**Comment by sybrew** [comment]
Settings like these (especially when I favor them) will be enabled by default 😄 But that's a good one! Cheers :)

**Comment by borisov87** [comment]
+1 i also want breadcrumbs everywhere

**Comment by madz00** [comment]
Yes please, I don’t want go back to Yoast 😄
In the meantime if I use the Navxt plugin there will be conflicts??

**Comment by sybrew** [comment]
@madz00 No plugin conflicts are known. Search engines render the breadcrumbs in the order that they're encountered, so TSF's breadcrumb list will always be used when enabled.

I just tested the plugin again and I see that the primary term selection doesn't change the behavior of NavXT. Support for this will be implemented later.

**Comment by madz00** [comment]
Perfect, I tested also the combo and everything seems fine. Also I discovered is a very refined plugins and with extensions for buddypress, bbpress and learndash (usually others fail to render correct breadcrumbs for these plugins).
Would be wonderful if the SEO Framework will support the integration with this plugin.

Thanks a lot for your help
