### ISSUE TITLE
Not output image for articler shema

### ISSUE THREAD

**Issue by borisov87** [sybrew/the-seo-framework#262]
I have featured image, also on Social meta settings fallbak is provided, but plugin not output image and i receive error

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdetoxproject.ivanborisov.com%2Ffood-navigator-podcast-rising-need-glyphosate-free-certification-reassure-worried-consumers%2F

**Comment by sybrew** [comment]
Hi @borisov87 

There's no need to worry about the error, Google states it's "recommended" but not "required" for **Non-AMP**:
https://developers.google.com/search/docs/data-types/article#type_definitions

That's why the rendered passed even though the image is missing.

Because the image object needs to be ***unique***, no fallbacks are used.
It'll only use the "Custom Social Image URL" from the post's respective SEO meta settings, or the "Features Image". The image will only be used when it's wider than ***696 pixels***.
