### ISSUE TITLE
Incomplete sitemap

### ISSUE THREAD

**Issue by CliveJD** [sybrew/the-seo-framework#296]
I am using polylang for a dual language site in English and Dutch with English as the default. The sitemap does not contain the Dutch versions of the pages

**Comment by sybrew** [comment]
Hi @CliveJD 

Multilingual sites shouldn't be connected through direct inclusion in the sitemap. Instead, they should be annotated as a different language.

So, the exclusion of other languages is intentional.
See #69 for more information.

WPML, Polylang, and other translation plugins should (and do) correctly output `hreflang` meta tags on the pages with alternative languages.
