### ISSUE TITLE
Problems with this plugin overwriting robots.txt

### ISSUE THREAD

**Issue by l3ku** [sybrew/the-seo-framework#339]
I recently discovered that using the WP core filter `robots_txt` with default parameters no longer works when using a self-made plugin after activating The Seo Framework. Here is the code I use in my own plugin:
```
add_filter( 'robots_txt', array( $this, 'custom_plugin_disallow_index' ) );
```
I found out that the problem originates from: https://github.com/sybrew/the-seo-framework/blob/e03888baa24b08deac108dadf341ae48aada828c/inc/classes/init.class.php#L648-L654
As can be clearly seen, the robots.txt output created in the function is not appended to the existing robots.txt content passed to the function, but completely overwritten. I was able to temporarily solve this problem by using a higher hook priority (11) than the default 10 in my own plugin:
```
add_filter( 'robots_txt', array( $this, 'custom_plugin_disallow_index' ), 11 );
```
I think that it is not good behaviour to overwrite the robots.txt content, as solving this problem required me to look through the code of this plugin to find out what exact priority this plugin uses with the WP core filter `robots_txt`. Or maybe at least provide some option to opt-out of this behaviour.

**Comment by sybrew** [comment]
[I did this](https://theseoframework.com/changelog/2-5-0-vibrant-seo/) because some popular plugins and even themes were adding conflicting data to it.
This makes sure it's always "correct"&mdash; at least, for more sites that don't require additional rules.

I'll look into making it optional. It'll probably be in a minor update. Thanks for highlighting it 👍

**Comment by ottok** [comment]
I am a[ big fan of SEO Framework](https://www.slideshare.net/ottokekalainen/technical-seo-for-wordpress-aka-stop-wasting-time-on-yoast) and this robots.txt messing is the only drawback it has in comparison to Yoast. I hope it gets fixed or at least the work-around well documented.

**Comment by sybrew** [comment]
The workaround is described correctly in the issue, use a priority higher than 10; floats are allowed:
```php
add_filter( 'robots_txt', $callback, 11 );
```

**Comment by sybrew** [comment]
It might be best converting this into an option: "Clean robots.txt"&mdash;or something along those lines.

When enabled, TSF will clean the robots.txt output, like it currently does.
When disabled, TSF will only add to it.

**Comment by sybrew** [comment]
I'm afraid I need to pull the "decisions, not options" card here. Overwriting the robots.txt is the sane thing to do, especially since we want a clean SEO experience that works out of the box. 

I understand that many site owners don't need this security, alas, many others do. Nevertheless, as always, if you want to ensure your output is appended, the WordPress WP_Hook API has got you covered.

I also added an entry in the filter API docs regarding this issue:
https://theseoframework.com/docs/api/filters/#add-robots-txt-rules
