### ISSUE TITLE
Carousels

### ISSUE THREAD

**Issue by vralle** [sybrew/the-seo-framework#342]
Hi!
Google can use the "[Carousels](https://developers.google.com/search/docs/guides/mark-up-listings)" markup. There are two types of markup. One type is used for listing posts on the pages such as archives. The second type is applied to the "all-in-one-page" list. I can be mistaken, but it seemed to me interesting. Could there be plans to implement Carousels?

**Comment by sybrew** [comment]
Thank you for pointing it out, I didn't know there were new carousels implemented.

Now, we're planning to implement every type of structured data, including these.
I've gone through great efforts to standardize this in the Extension Manager, it just needs to be utilized 😄 

That said, carousels are utilized in many forms. So, I think this needs to be split up into several issues:
1. Recipe
2. Film
3. Course
4. Article (already implemented via the Articles extension)

Because of this, I think it's best to close this issue and open new ones that are use-case specific.
If you have one in mind that you want to use, then I encourage you to point it out in a new issue. 👍
