### ISSUE TITLE
Generated Sitemap does not reflect correct translated slugs using WPML

### ISSUE THREAD

**Issue by abombelli** [sybrew/the-seo-framework#36]
Hello

Our site is multilingual so we use the plugin at wpml.org for translation.
The generated sitemap does not set the correct translated slugs in the <loc> tag.

This is the base language:

```
<url>
<loc>https://domain.ch/kontakt/</loc>
<lastmod>2016-09-13T10:49+02:00</lastmod>
<priority>0.9</priority>
</url>
```

And this is the translated version:

```
<url>
<loc>https://domain.ch/en/kontakt/</loc>
<lastmod>2016-09-13T16:32+02:00</lastmod>
<priority>0.9</priority>
</url>
```

As you can see "kontakt" is not change to the slug "contact" we have set for this page.

How can we solve this? Google Search Console returns errors, as the sitemap contains erroneous urls.

Let me know if you need the plugin to solve the issue.

Thanks,
Aldo

**Comment by sybrew** [comment]
Hi Aldo,

Thanks for opening this issue. I'm already working together with WPML to ensure the highest compatibility 😄. 

**Try and see solution:**
I believe there's a setting called "generate unique ID's" within WPML's settings &mdash; this allows for external programs to correctly identify the real permalink, including WordPress itself.
The reason I point you towards that option is because within the sitemap, the following function is used to create URLs: [get_permalink()](https://developer.wordpress.org/reference/functions/get_permalink/)... which propagates to [get_page_uri()](https://developer.wordpress.org/reference/functions/get_page_uri/).

Usually, translation plugins ensure compatibility towards other very popular plugins. 
Unfortunately, I'm doing all the work on this one... and there are limits. Alas, this is one of them and I can't fix this from within The SEO Framework.

**Recommended solution (overhaul):**
The easiest fix at your side would be to use subdomains instead of subdirectories, This is also highly recommended for SEO. 
In the upcoming update of The SEO Framework extra sitemap compatibility for this scenarios will be added as well.
If your site has been up in the air for quite some time, be sure to perform a test-drive to see if WPML will redirect users whom try to access the subdirectory URLs.

**Probably best solution for your website; another sitemap plugin:**
Use a sitemap plugin that has received compatibility from the WPML team themselves, like [Google XML Sitemaps](https://wordpress.org/plugins/google-sitemap-generator/).

I hope this all helps in some way. Cheers!

**Comment by abombelli** [comment]
Hi,

Thanks a lot for your feedback.

The "Try and see solution" did not work - The mentioned setting is already activated.
Probably I'll go for the additional Plugin.

Did you get a feedback from WPML regarding when they will solve the issue?

Thanks!

**Comment by sybrew** [comment]
Hi abombelli,

WPML currently offers no on-point plugin compatibility; [history has shown](https://github.com/wp-premium/sitepress-multilingual-cms/blob/master/changelog.md#compatibility-1) that they do not add specific compatibility towards plugins with some exceptions for Yoast, NextGen Gallery and Events Calendar and possibly a few others with over a million installations.

I'd suggest sticking with another sitemap plugin until these issues have been resolved. The issues are quite complex and unfortunately the sitemap won't receive the highest priority for improvements as it's becoming redundant in the eyes of Google.

I'll keep you updated once I have scheduled better compatibility. The earliest convenience would be at The SEO Framework 2.9.x.

Cheers!
