### ISSUE TITLE
Website name replacing the tagline in the homepage title

### ISSUE THREAD

**Issue by tombonez** [sybrew/the-seo-framework#363]
Hi,

I'm just in the process of setting up a new Wordpress build for a client and thought I'd give TSF a go (long time Yoast user).

So far it seems great, however on the homepage the tagline is being replaced by the website name in the title:

![screenshot 2018-09-25 at 13 50 29](https://user-images.githubusercontent.com/967673/46015993-8d850800-c0cb-11e8-9e41-843195b7cea3.png)

In the admin however it shows that this behaviour is incorrect (which it is):

![screenshot 2018-09-25 at 13 49 56](https://user-images.githubusercontent.com/967673/46016040-a2fa3200-c0cb-11e8-95c7-f00168c0f429.png)

(This is a separate fresh build of Wordpress to test this behaviour and it happens on both).

I have the homepage set via WP->Settings->Static Page->Homepage.

Disabling this corrects the issue.

If you need any more details just let me know.

Cheers,
Tom :)

**Comment by THBLX** [comment]
Hello, 
I am having the very same issue in my webshop after updating to the latest version.
[](https://www.tasty.green)

This is bad seo wise, so please help with an solution!

Best regards
Thomas

**Comment by sybrew** [comment]
Confirmed. Critical. Patch will be released ASAP.

**Comment by sybrew** [comment]
After updating, follow these steps:

<ol><li>Go to Google.com</li>
<li>Type in <code>site:example.com</code>, where example.com is your web address.</li>
<li>If the title of your homepage on Google is what it should be, no action is needed. Otherwise, continue.</li>
<li>Log into Google Search Console, you'll likely see the new interface.</li>
<li>Select "URL Inspection" at the left.</li>
<li>Type in your full home-page URL and hit return/enter (this might take a while).</li>
<li>Select "Request Indexing" (this might take a while).</li>
<li>Your title should be fixed within 2 days.*</li></ol>

*For me, it took 5 minutes, but anomalies may occur.
