### ISSUE TITLE
Errors and notices with the_seo_framework_version

### ISSUE THREAD

**Issue by Narek13** [sybrew/the-seo-framework#378]
Hi, there are an errors and notices in your plugin
```
Notice: the_seo_framework_version is deprecated since version 3.1.0 of The SEO Framework! Use THE_SEO_FRAMEWORK_VERSION instead. In /home/152014.cloudwaysapps.com/zsxkdazcek/public_html/wp-includes/class-wp-hook.php on line 310.
Notice: the_seo_framework_active is deprecated since version 3.1.0 of The SEO Framework! Use the_seo_framework()->loaded instead. In /home/152014.cloudwaysapps.com/zsxkdazcek/public_html/wp-includes/class-wp-hook.php on line 286.
Error: the_seo_framework()->theme_title_doing_it_right() is not accessible. In /home/152014.cloudwaysapps.com/zsxkdazcek/public_html/wp-includes/class-wp-hook.php on line 310.
```
we had the same issue in earlier versions and you fixed them, now the issue returned

**Comment by sybrew** [comment]
Hi there 😃 

The [Title Fix plugin](https://wordpress.org/plugins/the-seo-framework-title-fix/) is no longer supported and was eradicated by the WordPress plugin team after I stated that it was deprecated. It's nice to see it's still getting downloads, but it's no longer deemed compatible since The SEO Framework 3.1.

It's been long moved as an extension for the [Extension Manager](https://wordpress.org/plugins/the-seo-framework-extension-manager/). Therewith, it's been improved further and won't output the warnings: https://theseoframework.com/extensions/title-fix/
