### ISSUE TITLE
Open graph and Twitter card titles have site name

### ISSUE THREAD

**Issue by joppuyo** [sybrew/the-seo-framework#394]
Facebook recommends not having the site name in open graph title in their [documentation](https://developers.facebook.com/docs/sharing/webmasters/)

> og:title
> The title of your article without any branding such as your site name.

Twitter's [documentation](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) doesn't explicitly state this but all their examples don't have any branding in the title tag.

In any case, both platforms already have the site URL visible in the card so having the site branding in the title is redundant. However, this plugin will add the site name in the OG/Twitter titles by default.

I would prefer stripping the branding from the title by default in this plugin but it could be an option if the current behaviour is something people expect.

Are there any filters that can be used to strip the site name from social media titles right now?

Just for reference, here's what the current system looks like:

![site-name-in-social-media-title](https://user-images.githubusercontent.com/1595438/50188121-2624d000-0329-11e9-908e-4f6e586b04b6.png)

And here what it would look like without the titles:

![site-name-not-in-social-media-title](https://user-images.githubusercontent.com/1595438/50188099-10170f80-0329-11e9-80c3-e1151be6d5e0.png)

**Comment by sybrew** [comment]
Thanks for opening this issue!

Unfortunately, a filter that discerns the state (social/meta title) isn't available. You could "guess" it, but I advise not to partake in such endeavors.

I'm slowly moving towards it. For example, in 3.0.4, the blog name is no longer appended to the custom social titles.

> The social titles, when filled in, will exclude additions (like the site name) automatically.
([source](https://theseoframework.com/?p=2264#detailed))

Methods `get_generated_twitter_title()` and `get_generated_open_graph_title()` are intermediate placeholders for this functionality. You can see they simply forward their call to the meta title as of now.

We need to introduce this change needs in the form of an option. Because there's an issue. Here are both sides:
1. Some site names **aren't** descriptive enough, and appending the blog name **will help**.
2. Some site names **are** descriptive enough, and appending the blog name will **be redundant**.

These issues need to be described above the option. So the user can make an educated decision.

Here's my plan, for the option to remove the titles:
1. The option will be **enabled** by default on **new** installations.
2. The option will be **disabled** by default on **old** installations.

Thanks to v3.1.0, I can implement this quite easily. As such, I'm moving this to the next major release.

**Comment by sybrew** [comment]
I'm punting this to a future release as this requires more consideration on changing both the PHP and Javascript API.
