### ISSUE TITLE
Meta titles in different languages

### ISSUE THREAD

**Issue by colomet** [sybrew/the-seo-framework#401]
what if we require two languages for metatitles and descriptions? 

normally we require in one language, but some times we may need two languages, the language of the content, and english, so more people can understand what´s about

(in my situation, we do textbooks, so books are for teaching english but created in other languages)

**Comment by colomet** [comment]
our books are in spanish, but we teach english. Is created in both languages, so there are not translations of pages. We offer the content in one language.

But, we would like to be able to have metatitles and descriptions in both languages. But we do not use a translation system, just one language in the content (english all the time)

**Comment by sybrew** [comment]
Search engines and social networks can only take one title and one description from a page. 

It's not possible to supply information for alternative languages unless you create a new (localized) page. Then, I recommend translating the whole page so that the bounce rate won't be too high.

For that, you'd want to supply an `hreflang...alternate` meta tag: https://support.google.com/webmasters/answer/189077?hl=en
However, TSF has yet to add support for this feature. Related: #69
