### ISSUE TITLE
GSC doesn't recognize unslashed homepage in sitemap

### ISSUE THREAD

**Issue by koreos** [sybrew/the-seo-framework#408]
Hi, how can I add slash on the end of my main domain in sitemap.xml like https://domain.com/ ? Because Google Search Control tell me that not see this URL when I check main domain. Please help

**Comment by sybrew** [comment]
Hello 😄 

You can add a slash in at the WordPress Permalink settings, in the Custom Structure input:

Before:
![image](https://user-images.githubusercontent.com/7662236/52204770-5c84c300-2875-11e9-8e1b-d93c38e577f1.png)

After:
![image](https://user-images.githubusercontent.com/7662236/52204760-568ee200-2875-11e9-9ac2-8fedf2dfa128.png)

I'm not sure if this is related to the issue you're experiencing, however. 

If you're still experiencing this issue, please make a screenshot or copy the exact text of what the Search Console tells you. Thanks!

**Comment by koreos** [comment]
Hi :-) 

no no no , it will be kill my all url links without slash on the end, I need only on main domain, for example https://wpart.pl/page-sitemap.xml

Google Search Control know my main domain but says that url of it is not in my sitemap.xml and it is true because there is without slash on the end.

**Comment by koreos** [comment]
I think that canonical url of main domain should be with slash on the end always..? This is with all another WP SEO Plugins I think..

**Comment by sybrew** [comment]
I find it hard to believe that Google's Search Console complains, as  [IETF's RFC2616](https://tools.ietf.org/html/rfc2616#page-20) clearly states:
> An empty abs_path [(i.e. path after the domain name)] is equivalent to an abs_path of "/".

Could you forward Google's report to me? If you'd rather keep this confidential, you may [contact me here](https://theseoframework.com/contact/). I'm also going to test this on one of my dormant sites.

Note that when you add a slash in the permalink settings, WordPress automatically 301-redirects the visitors from the old URLs to the new. So, no issues are there, as search engines will follow and abide by the change without affecting ranking. The SEO Framework follows suit by updating the canonical URL.

I think the browsers that are obscuring (Firefox, Safari, Chrome) or enforcing (IE, Edge) confuse many people (you're not the first asking this); but, please note that the plugin is correct in its behavior. But, at the same time, other plugins aren't incorrect on this behavior.

In any case, because the browsers either obscure or enforce this, your visitors won't notice it. Also, they really don't care about the URL. They only care about the story, benefits, and the brand behind the URL. I believe you should always focus on improving those things 😄.

**Comment by koreos** [comment]
For test I used Rank Math SEO and there is always slash on the end of main url (canonical) domain "domain.com/" even I set subpages without slash "domain.com/subpage". I suppose that another wp seo plugins has the same.

**Comment by sybrew** [comment]
Cheers 😄 

I believe this to be a bug in Google's Search Console, and you can safely ignore it for now. 
Note: The **URL is indexed**, but not submitted in the sitemap.

I'm currently testing this behavior, which can take up to two weeks. I'll report back with the results, and forward the bug to Google if they're positive.

**Comment by koreos** [comment]
Ok, thank you. :-)

**Comment by sybrew** [comment]
Confirmed. Note that the "Open Report" page doesn't highlight an issue with the homepage, which implies inconsistency, and in extent, a bug.

![image](https://user-images.githubusercontent.com/7662236/52694322-9175d180-2f69-11e9-8799-3610da9a0d74.png)

I'll wait for a few more days, as the report may be awaiting data propagation.

**Comment by koreos** [comment]
Ok, thank you!
