### ISSUE TITLE
Finnish language has a overly long name on the sidebar

### ISSUE THREAD

**Issue by Ciantic** [sybrew/the-seo-framework#418]
Hope this is a mistake, latest update brought translation to the sidebar that is huuuuge:

![image](https://user-images.githubusercontent.com/64731/53955265-35721900-40e1-11e9-87d7-350782ff4ce3.png)

It looks awful. "SEO" is fine, or "Hakukoneet / SEO" if it fits. Finns use the term SEO anyway, so keeping it short would be best.

**Comment by LeBaux** [comment]
Thanks for reporting, I corrected the Finnish translation, it now simply says SEO :) However, since I do not speak the language I can not approve the change. Other community editor needs to it and that might take some time. If you run into any other problems with translation, please let us know (you can post here)! It is always a huge help since we can't really judge the quality of all the translations.

Alternatively, you can add/edit translation yourself in the [WordPress directory](https://translate.wordpress.org/projects/wp-plugins/autodescription/stable/fi/default). If you are not familiar with GlotPress, it is a very simple system and you need is the account on w.org to contribute.

**Comment by sybrew** [comment]
I suggested HKO, as per the Polyglots' Finnish glossary.

![image](https://user-images.githubusercontent.com/7662236/54042736-25366880-41cb-11e9-89c7-72aa1a86f8ae.png)

**Comment by sybrew** [comment]
It seems to be translated within a day, which is an awesome feat. 

https://twitter.com/TeemuSuoranta/status/1103605598573289472

With that, oversights like these aren't unlikely. I went out of my way and suggested a few other improvements as well. I hope they get approved (or even improved) soon 😄

**Comment by Ciantic** [comment]
I've never heard anyone use "HKO" in finnish, I think the sidebar word should be recognizable, and abbreviating it to HKO would make it useless. Either longer word that fits or known word like SEO, even clients use that word rather often.

I think I can also summon the @teemusuoranta here.

**Comment by TeemuSuoranta** [comment]
Hi!

Thank you for the heads up! The plugin has been translated mainly by 4 people and I have edited and approved about 80% of strings. I have tried to unify all translations and get rid of suggested finnish abbreviations (like HKO) as they are not in general use even though technically correct.

I was able to test the translations a bit better now and made about 30-40 tweaks and corrections including a shorter name for the sidebar (settled into "SEO-asetukset" as other were too long and it makes sense to find "SEO" word in menu after installing plugin that has SEO in its name). Thus this ticket can be closed.

If you find translations that make no sense, you can send suggestions or ping Finnish Polyglots directly in WordPress Finland Slack (https://fi.wordpress.org/chat/) at channel #kielitaiturit.
