### ISSUE TITLE
How to restrict the sitemap with regards to bbpress/buddypress?

### ISSUE THREAD

**Issue by ovizii** [sybrew/the-seo-framework#42]
Here is a sample sitemap with 708 entries: https://www.die-kellerkinder.eu/sitemap.xml 

I would like to reduce that number and NOT have replies indexed as they are the majority of those entries.

Any way to achieve this?

**Comment by sybrew** [comment]
Hi @ovizii,

Thanks for this! I now noticed I made [a typo](https://github.com/sybrew/the-seo-framework/blob/275b4c0c91d45060a6ac030a9467d60a1bfa9c9f/inc/classes/sitemaps.class.php#L649) in the CPT sitemap generation :(.

Anyway, in order to remove replies from the sitemap, please use the following snippet, using [this filter](https://github.com/sybrew/the-seo-framework/blob/275b4c0c91d45060a6ac030a9467d60a1bfa9c9f/inc/classes/sitemaps.class.php#L572):
```
add_filter( 'the_seo_framework_sitemap_exclude_cpt', 'my_sitemap_exlusions' );
function my_sitemap_exclusions( $exclusions = array() ) {

	$exclusions[] = 'replies';
	//* You can add more exclusions, for example:
	$exclusions[] = 'forums';

	return $exclusions;
}
```

You can reset the sitemap's cache by updating a post/page, or by re-saving the SEO Settings.

I hope this helps! Cheers 😄

**Comment by ovizii** [comment]
thanks for the quick reply and the snippet.

hm, that didn't seem to work. Are you sure I need to exclude "replies" and not "reply"? 
I've edited a page and re-saved the settings and invalidated

**Comment by sybrew** [comment]
Hi ovizii,

I'm not sure if it's reply or replies.

The only way you can be certain is to [dump the current post type](https://developer.wordpress.org/reference/functions/get_post_type/) on the said page, or dump all public post types and make your picks from there: `get_post_types( array( 'public' => true ) );`

But before that, I'd suggest trying `reply` :).

**Comment by ovizii** [comment]
hm, I dumped all of them:
`<?php
foreach ( get_post_types( '', 'names' ) as $post_type ) {
   echo '<p>' . $post_type . '</p>';
}
?>`
Result:

> post, page, attachment, revision, nav_menu_item, forum, topic, reply, bp-email, postman_sent_mail

so I then inserted reply into your previous snippet and yet no change. Any more ideas? Does your snippet work for you? Here is what is inside my functions.php
`/* Added to remove replies from the sitemap */

add_filter( 'the_seo_framework_sitemap_exclude_cpt', 'my_sitemap_exlusions' );
function my_sitemap_exclusions( $exclusions = array() ) {

    $exclusions[] = 'reply';
    return $exclusions;
}
`

**Comment by sybrew** [comment]
Hi @ovizii, 

I still have a very hard time using bbPress on my test server... no settings for the forums are shown 😕.
Nevertheless, I figured it out 😄. 

It's not working because I made a typo:
```
my_sitemap_exlusions
my_sitemap_exclusions
```

You'd have to change the function name or the callback name accordingly so they're equal.

In your case, this snippet should work as expected, don't forget to flush the sitemap's cache by re-saving the SEO settings:
```
add_filter( 'the_seo_framework_sitemap_exclude_cpt', 'my_sitemap_exclusions' );
function my_sitemap_exclusions( $exclusions = array() ) {

    $exclusions[] = 'reply';

    return $exclusions;
}
```

Cheers!

P.S. You'll need to use three backticks with a line-feed/return to write code blocks at GitHub.

**Comment by ovizii** [comment]
Hi and thanks for the help so far. Absolutely no need to explain yourself, this is outstanding support you're doing here for free. Thanks for the tip with the "```" :-)

I should have looked closer at the snippet you provided, I could have caught that typo myself. 

I can confirm this all works as expected! Thanks a lot, maybe add this to the plugin FAQ as a link?

**Comment by sybrew** [comment]
Anytime! I'm glad it worked out.

A knowledge base/FAQ is certainly planned, and I have more than enough data to fill it in 😄.
Even more so, an automated plugin function documentation system is planned, as seen on [https://developers.wordpress.org/](https://developer.wordpress.org/reference/). But that's a project for later.

For now, filters, constants and other things are shown at [The SEO Framework API docs](https://theseoframework.com/docs/api/). It requires some updates (rather a complete rework 😝), but most information is already present.

Have a wonderful day!

**Comment by cjyabraham** [comment]
My sense is that this method no longer works?  I can't find the `the_seo_framework_sitemap_exclude_cpt` hook in the plugin code.

**Comment by sybrew** [comment]
Hi @cjyabraham 

For best performance, I recommend using `the_seo_framework_sitemap_supported_post_types` now. It's a sequential array of supported post types.

```php
add_filter( 'the_seo_framework_sitemap_supported_post_types', function( $post_types ) {
	return array_diff( $post_types, [ 'exclude_this_post_type', 'exclude_me_too' ] );
} );
```

Cheers!
