### ISSUE TITLE
Custom name for sitemap

### ISSUE THREAD

**Issue by uok** [sybrew/the-seo-framework#426]
Hello,

Thanks for this amazing plugin, it works really great!

My suggestion for the sitemap: 
Let users enter a custom filename, e.g. "myhiddensitemap.xml" for the sitemap.
This helps blocking unwanted crawlers from simply requesting sitemap.xml (even if it is not in robots.txt)
Thanks!

**Comment by sybrew** [comment]
Hello, and thanks 😄! 

The WordPress rewrite engine isn't the easiest thing to work with, and the name is hardcoded. This issue is a corner-case, and it probably won't make it as an option. If anything, we'd have to add a filter or constant, which you must add to an advanced mu-plugin.

If bots are harming your website, then you may wish to consider switching hosting providers. Alternatively, many bots have a user-agent or known IP range, which you can more effectively block via a rewrite rule, like in the `.htaccess` file.

Moreover, we're going to add more sitemap types (see #31), and this addition will hinder that process. So, I'm going to park this feature and revisit if after 31 is implemented.

Cheers!

**Comment by sybrew** [comment]
From v3.3.0, you can use the filter below to adjust the base sitemap endpoint.
In the example below, it's changed to "sitemap-900142.xml" 🔺 

```php
add_filter( 'the_seo_framework_sitemap_endpoint_list', function( $list ) {

	$list['base']['endpoint'] = 'sitemap-900142.xml';
	$list['base']['regex']    = '/^sitemap\-900142\.xml/';

	return $list;
} );
```

**Comment by uok** [comment]
Thanks a lot, works great!
