### ISSUE TITLE
Automatically switch to small twitter card summary if social image is too small

### ISSUE THREAD

**Issue by devNigel** [sybrew/the-seo-framework#428]
Currently, TSF is switching to site icon if no image is found from webpage. The large version of Twitter Summary Card looks out of place with something like site icon inside it.

In those cases, it would be better to automatically use smaller version of Twitter Summary Card even if user has set TSF to use summary with large image.

Site icon would look just perfect with the small Twitter Summary Card.

**Comment by sybrew** [comment]
I honestly wasn't aware that Twitter supported imaged for `summary`, as opposed to only for `summary_large_image`. Yes, I'll gladly implement this.

**Comment by hiNigel** [comment]
That would be great! 

Twitter has not updated their [documentation page](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary) properly. Their example is showing `summary_large_image `instead of `summary`

**Comment by sybrew** [comment]
Yea, I already notified them on that with a frowny face :)

**Comment by HelaGone** [comment]
Hello.
I have this problem:
TSF Is not taking into account the featured image of the post and instead, it's placing the site icon in the og:image and twitter:image tags even though the post has its own ft image and therefore when a post it's shared  it has the site's logo instead of the featured image.  I'm not sure why this is happening. Can you please tell me how can I troubleshot this issue. 
When I debug the post with the OpenGraph debugger, the featured image is set properly, but when the post is debugged with the Twitter Card Validator the featured image is not set but the site logo instead. Also, when I try to share the post through Whatsapp or Telegram it shows the site's icon and not the featured image.

**Comment by sybrew** [comment]
Hi @HelaGone 

Could you open a new topic on this matter? Or, better yet, [contact me](https://theseoframework.com/contact-us/) with details, like the affected pages, the image you tried to set, and anything else you think that might help.

I think that the issue you're experiencing is caused by duplicated OG/Twitter card meta tags. These duplicated tags may come from the theme you're using, or from another plugin.

**Comment by HelaGone** [comment]
Hi @sybrew 
The problem was more or les solved changing the card type for Twitter in the social media settings from summary_large_image to summary. Of course this is a temporal solution since all our publications in social media are posted with the large image card and we want to be consistent. 

I wonder if the featured image size is a matter. All our posts have their own featured image and each image is at least 1200x675px which i think it's ok. 

Nevertheless I'll fill the contact form with the details of the problem. 
Thanks in advance!

**Comment by sybrew** [comment]
Summary images should be at least 144x144px, and at most 4096x4096px, the images must (will be cropped to?) have a ratio of 1:1.

Summary Large Image cards start at 300x157px, and at most 4096x4096px, the images will be cropped to a ratio of 2:1.

**Comment by HelaGone** [comment]
@sybrew 
Then the image's dimension is not the issue, right?
I've double checked that there isn't any other plugin inserting those meta tags. And since our theme is an in-house developed theme that is discarded too.

**Comment by sybrew** [comment]
Correct. But the image-generation part is unaware of the card type. 
However, this will change when this GitHub-issue is tackled.

I tried to replicate what you sent via email, and what you're experiencing is a bit more difficult to pinpoint than I thought. 
We're greatly **off-topic** here. So, let's continue via email. There's no need to say "OK" to this message, either 😅

**Comment by sybrew** [comment]
Merging this issue with #525, for they both alluded to an "auto" selection.
