### ISSUE TITLE
Title filter hooks not run

### ISSUE THREAD

**Issue by mundschenk-at** [sybrew/the-seo-framework#436]
**Describe the bug**
As a follow-up to https://wordpress.org/support/topic/title-with-tags/#post-11531777 and https://github.com/mundschenk-at/wp-typography/issues/246: The `document_title_parts` and `wp_title_parts` hooks are not applied by The SEO Framework, breaking compatibility with plugins that rely on those standard filter hooks.

**Comment by sybrew** [comment]
`wp_title_parts` and `wp_title` gave too many issues: all the filters overlapped, it was chaos, and everything was a bug.

To resolve this, [in WordPress 4.4](https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/), `pre_get_document_title` was introduced: it short-circuits the function. Effectively, using that forces the function not to run, and we were allowed to replace its contents. Theme authors were imposed to implement the new title functions, and that was a good day.

Now, I won't say that those additions aren't beneficial for other developers solely relying on them; but the fact is that they shouldn't: it will break the expected and natural behavior that users have come to expect. The users expect a simple, self-set input, and expect a simple, unadjusted output.

Effectively, adding back `document_title_parts` will create unexpected behavior, it will bring back the chaos.

Moreover, then this would then also be a bug in Yoast SEO, All in One SEO Pack, and many other plugins that filter the document title. I don't think you'll win this fight with the big guys.

The reason you won't see this issue in Yoast SEO is that there's no need to strip the tags after the fact; they disregard all other plugins and don't rely on standard WordPress functionality. As such, they don't have the filters wp-Typography acts upon. They can disregard others, as they're dominating the market; they force everyone to bow to them instead. It is why using their plugin is such a buggy experience, and it is why you see many plugins adding faulty compatibility layers towards Yoast SEO.

However, you will see this issue recur in All in One SEO Pack.

The reason we see HTML tags appear in the document title with wp-Typography is that it adds HTML tags to filters that don't expect them and tries to clean itself up after the fact. Not every filter or action is always available that allows you to complete a circuit--yes, there are exceptions, like `shutdown`.

The resolution for wp-Typography would be not to clean up after itself. It makes for easier maintenance, as well, as you can remove `process_feed()` and all related functionality.

Instead, removing these filters, and solely rely on filtering `the_title` would be great:
```
single_post_title
single_cat_title
single_tag_title
single_month_title
single_month_title
```

With those removed, all front-end titles would still be adjusted&mdash;unless themes choose not to use them; but that's their fault&mdash;, but the document title will stay clean.

**Comment by mundschenk-at** [comment]
I disagree, @sybrew.[ `document_title_parts` was also introduced in 4.4](https://make.wordpress.org/core/2015/10/20/document-title-in-4-4/), so it's not a legacy API by any stretch. As you have noticed yourself, Yoast strips tags from the generated `<title>`, which is correct behavior. All in One SEO Pack uses the old-style `wp_title` filters, which works fine as well.

While I'll look at your suggestion, it would probably break existing site themes that rely on the `single_*_title`  functions being properly filtered. Anyway, defensive programming is SOTA for anything where you can't be sure of your input parameters, so stripping tags before outputting the title is still the right thing to do.

**Comment by sybrew** [comment]
It may be "optimized" for that file, but that's [anecdotal evidence](https://en.wikipedia.org/wiki/Anecdotal_evidence): the fact remains that WordPress uses it in places where no HTML is allowed, like in feeds. It doesn't say anywhere in the API that HTML is expected.

Let's go back to the early days of WordPress. This all stemmed from the very first WordPress theme doing it right (escaping the title), where others were doing it wrong (not escaping). See https://core.trac.wordpress.org/ticket/1371. There, they also mention RSS feeds as an argument.

> It's a title, not HTML output.

Titles were never expected to contain HTML; that users can do that is spun off from security issues in third-party themes (not escaping the output...), which eventually turned to ill-advised recommendations, followed by the WordPress team not wanting to break sites, and now solely relying on user capabilities for titles, like `unfiltered_html`.

It boils down to that the theme should style the title via CSS and other means, and the user shouldn't.

You've misread my interpretation of the Yoast and All in One SEO Pack issue. 
1. wp-Typography creates this issue for All in One SEO Pack, as well. Moreover:
   1. The use of `wp_title()` is forbidden in themes submitted to WordPress.org since late 2014.
   1. They are also four years behind... Ref [1](https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1751) & [2](https://core.trac.wordpress.org/ticket/18548)
2. Yoast doesn't care, and they force other plugins to create compatibility for Yoast SEO, next to WordPress. They add a whole new API layer on top of WordPress and shut off WordPress' default API.

There's nothing wrong with defensive programming. However, when you act upon an API, you should not trickle it down to later parts to fix your mistakes. Especially not if one can disable portions of the code&mdash;you can not expect that code to run.

As a final note, if I add the filter while other plugin authors are not expected that to run if the function has been short-circuited, it'll create an issue for them: duplicated titles, double escaping, wrong order of things, transformed parameters, etc.

Now, I suggest following up on my recommendation. If theme authors choose not to implement default WordPress functionality, it's on them not adhering to the API; not us. You're now forwarding this issue downstream, while it should be going upstream to the actors initiating the calls. It's a rabbit hole either way, so I understand why you commend me for changing it.

**Comment by mundschenk-at** [comment]
I don't agree with all your arguments (going to the API documentation is not "anecdotal evidence"), but I've checked up on all those legacy hooks (they have been in the plugin since before I took it over and I am reluctant to break things for 10.000 users by changing long-standing behavior); some were definitely used incorrectly and some are probably edge cases. I'll remove a whole bunch (and add one) in the next release.
