### ISSUE TITLE
the_seo_framework_sitemap_additional_urls filter not work...

### ISSUE THREAD

**Issue by 9585999** [sybrew/the-seo-framework#467]
hi, I'm trying to use a filter [the_seo_framework_sitemap_additional_urls](https://theseoframework.com/docs/api/filters/#sitemap-related) to add links of category pages and tags to the site map, all to no avail...

If you have any ideas what could be the problem?

**Comment by sybrew** [comment]
Thanks for reporting this! This is caused because our filter processor creates a multidimensional array, whereas the parser expects an iterator output.

The next update will fix this by offloading the filter input as a generator.

P.S. The function in our API docs is outdated and calls a (now) deprecated function. We'll update the docs ASAP.
P.P.S. You can now add sitemaps to the plugin. We created a rudimentary [concept plugin for term sitemaps](https://github.com/sybrew/tsf-term-sitemap) you may wish to expand.

**Comment by 9585999** [comment]
@sybrew

Thanks for the answer. This clarified the situation. :)
