### ISSUE TITLE
The SEO Framework sitemap xml only showes main language

### ISSUE THREAD

**Issue by Mediawolf1** [sybrew/the-seo-framework#481]
Hi!
I have several multilanguage sites using WPML and The SEO Framework (https://theseoframework.com). The sitemap.xml file only list the mail language. On the eitapp.com site that would be finnish. The other language of this site is swedish.

I can see the main sitemap here: https://eitapp.com/sitemap.xml
but the swedish pages are not listed. They are in a diffrent sitemap file:
https://eitapp.com/sv/sitemap.xml

As I have read on the net there should only be 1 sitemap.xml file with all pages and languages listed. How can I get this?

**Comment by sybrew** [comment]
Hello!

You can submit multiple sitemaps to search engine networks via their webmaster tools.

The single-language-based model is intentional and was introduced in #293.

If you want mixed languages in one sitemap file, you must annotate them as such. For that, see #69 and https://support.google.com/webmasters/answer/189077.
However, we have no plans of introducing that annotation in the sitemap, as `hreflang` metatags (by WPML et al.) are sufficient.

**Comment by tobias992** [comment]
Old thread but I still have the same issue. Easy website with german (default) and english translation. But when i visit https://example.com/en/sitemap.xml I get an 404 (page not found) error. There is just the german sitemap.

On pages we use correct alternate-hreflang links but no english sites gets indexed. Because of this I believe, google needs an english sitemap.

**Comment by sybrew** [comment]
Hi @tobias992,

Thank you for the report. 

> no english sites gets indexed. Because of this I believe, google needs an english sitemap. 

This statement is false. A sitemap is completely optional and is not required for indexing. 
Google is confusing about this: the "sitemap indexing report" looks like it's the "indexing report", but the sitemap report is a focused report -- the primary indexing report lists all pages available on Google.

In any case, it's best to open a new issue, especially since this one is old and closed and won't be reopened.
In that new issue, could you share more details, such as which translation plugin you're using? A direct URL to the site would also be helpful.

**Please note:** If you're using TranslatePress, see https://github.com/sybrew/the-seo-framework/issues/615. It's already being looked at, and we already have everything we need to resolve this (if feasible).
