### ISSUE TITLE
SEO Framework's XML Sitemap - deleted pages still in sitemap 

### ISSUE THREAD

**Issue by TopherHough** [sybrew/the-seo-framework#483]
**SEO Framework's XML Sitemap - deleted pages still in sitemap **

**How to reproduce the bug**
1. Go to 'https://www.executivela.com/sitemap.xml'

![The SEO Framework  XML Sitemap issue - deleted pages are still in the sitemap](https://user-images.githubusercontent.com/44450316/67151700-8b658c80-f27e-11e9-99ab-f94495284458.jpg)

**Comment by sybrew** [comment]
Hello!

Please try clearing the cache via your caching plugin; it doesn't seem to have responded to the deletions. Those pages still exist to the public and are accessible from my end.

**Comment by TopherHough** [comment]
I tried that several times. I cleared the SiteGround hosting catch... That
doesn't work.

**Comment by sybrew** [comment]
Hi @TopherHough,

The issue is that the pages are still available, like this one: `https://www.executivela.com/a-post-without-image/`.

When you delete those example pages, they'll also be removed from the sitemap. If you can't delete the pages, for any reason whatsoever, please reach out to Siteground support. I'm sure they can help you with that. Cheers!

**Comment by sybrew** [comment]
The sitemap looks good to me now. Cheers! 😄

**Comment by TopherHough** [comment]
Thank you!

Guess what the problem was  - - - It was dummy example "Posts" that were
from the theme creating pages that showed up in the XML Site Map.

I deleted the dummy posts and now the XML Site Map is accurate.

Thanks!



*Christopher Hough*

*310.493.4732*

*topherhough@gmail.com <topherhough@gmail.com> *
