### ISSUE TITLE
Link Rel Canonical with wrong permalink

### ISSUE THREAD

**Issue by eduardoarandah** [sybrew/the-seo-framework#487]
With recent wordpress version 5.3 something´s wrong with link canonical. 
I've resaved permalinks, disabled caches and still I get this wrong url. 

What could be happening? 
my timezone is -6 and it's 9pm here
could it be taking utc instead of current timezone?

![Sin título](https://user-images.githubusercontent.com/4065733/68823226-bca46300-0658-11ea-8a0b-50efdd11a0e3.png)

**Comment by sybrew** [comment]
Hello!

WordPress finally fixed their timestamps in 5.3, which we've been rectifying for years. We do so via PHP, whereas WordPress seems to be doing things differently. I don't know where this is going wrong, and I must investigate further.

To determine the criticality of this issue, I'd like to ask you this: 
When you click the canonical URL, are you redirected back from `/14/` to `/13/`? Do you see a 404 page? Or, is that URL "just" working?

Thanks!

**Comment by sybrew** [comment]
Related core ticket: https://core.trac.wordpress.org/ticket/48623

**Comment by eduardoarandah** [comment]
Hey! 

Yeah it’s super critical. 

I’ve had to migrate 3 clients to another plugin because they “can’t share to Facebook” 

Twitter works fine. 

Links with date 13 appear as 14. I’m in Mexico, utc -6 

I also read something about dates in last wp release.

**Comment by sybrew** [comment]
This issue boils down to that WordPress doesn't cope well with timezone settings in PHP for the permalinks. This issue isn't necessarily instigated via a plugin, but php.ini settings can also cause broken links for WordPress.

My main problem with this is that the timestamps of TSF (sitemap, Facebook article, Schema.org) are still correct. It is that the permalinks handed by WP are broken since WP 5.3 because they now use `gmdate()` ([source](https://github.com/WordPress/WordPress/blob/5.3/wp-includes/link-template.php#L215)). Previously, it was `date()` ([source](https://github.com/WordPress/WordPress/blob/5.2.4/wp-includes/link-template.php#L215)), and that worked perfectly.

Further reading (and a WP Core solution) is provided in [my comment here](https://core.trac.wordpress.org/ticket/48623#comment:30).

Alas, I think we'll need to move forward on this and create an update or temporary patch solely dedicated to this issue. The Core Trac ticket doesn't seem to be going anywhere anytime soon. I hope the "critical" priority change will help speed it up, however.

I haven't worked out the details, but we'll likely start enforcing "UTC+0"-time (via `date_default_timezone_set()`), instead of the real site time for TSF generation. That should fix the permalink issue, if only temporarily. This change can break other timestamps, so it may take a few days before a proper solution is out.

**Comment by sybrew** [comment]
The component maintainer "Rarst" notified that the use of `gmdate()` is intentional, since the whole of WP shifted from `date()` to that. This makes sure the whole system revolves around one standard.

However, the permalink generator shouldn't have gotten that change, since the rewrite system uses the post date without manipulating it. Therefore, this was an oversight&mdash;so although `date()` worked, it worked by accident... and now it doesn't, also by accident.

The WP Core patch proposed already solves that by maneuvering around this limitation. 

With that, I'm not sure if I should fix this via The SEO Framework. The DateTime manipulation in TSF is a catch22 situation. We shouldn't change it; but, because others change it, we must change it regardless. This is something other plugins also do, and it'll never end.

In the meantime, we'll see if falling back to UTC also works with the new changes (and variables/functions) in WP 5.3. That'll iron out the way we work with dates forever.

**Comment by sybrew** [comment]
WordPress 5.3.1 is proposed for release on [December 11, 2019](https://make.wordpress.org/core/2019/11/20/dev-chat-summary-november-20-2019/). So, we'll move on with a patch; commits will be rolling in soon.

Tests with WP 5.2 and below still need to be conducted. The releases should be out within 24 hours from now.

**Comment by sybrew** [comment]
All tests passed.
