### ISSUE TITLE
Change title for "Tag"

### ISSUE THREAD

**Issue by royashgit** [sybrew/the-seo-framework#492]
Hello,

How could we change all titles for tags to automatically read instead of:

`<title>Tag: New York</title>
`

`<title>New York - Look at latest News</title>
`

many thanks
Andrew

**Comment by LeBaux** [comment]
When it comes to SEO, you should edit your tags separately and each one should be unique. You can do that in:

Posts > Tags

**Comment by royashgit** [comment]
thanks LeBaux, but I was wondering if there ways a way to change the defaults in any case!

**Comment by sybrew** [comment]
Hello!

In the SEO title settings, you'll find a toggle to remove them site-wide, as shown in the image below:
![image](https://user-images.githubusercontent.com/7662236/72380452-bb092100-3715-11ea-96a5-e574b679f791.png)

I'm considering adding a filter for this in the next update so that you can adjust this on a per-term(-type) basis. The only issue we have is that we must remove some caching for the SEO Bar, which can harm performance when we add the filter.

**Comment by sybrew** [comment]
In 038ec7f69996227ebc128fc76a7e715b93ba268c the filter was added, with SEO Bar support.

The filter is: `the_seo_framework_use_archive_prefix`. In combination with filter `the_seo_framework_the_archive_title`, you'll have full control over the prefix behavior.

Will ship with TSF v4.0.5.
