### ISSUE TITLE
Notice: the_seo_framework()->get_social_image_url_from_post_meta() is deprecated...

### ISSUE THREAD

**Issue by TopherHough** [sybrew/the-seo-framework#497]
Hello, thanks for your help

All of my blog pages have a strange SEO Framework Error Message

The Error Message is: 
"Notice: the_seo_framework()->get_social_image_url_from_post_meta() is deprecated since version 4.0.0 of The SEO Framework! Use the_seo_framework()->get_post_meta_item( '_social_image_url' ) instead. In /home/magnetmk/public_html/wp-content/plugins/the-seo-framework-extension-manager/extensions/free/articles/trunk/inc/classes/front.class.php on line 449.

Please see top of each of these pages:
https://magnetmktg.com/7-voice-seo-factors-for-your-business/
https://magnetmktg.com/6-tips-for-google-analytics-after-set-up/
https://magnetmktg.com/blog-23-popular-social-media-acronyms/

![SEO Framework issue -Notice the_seo_framework()-get_social_image_url_from_post_meta() is deprecated since version 4 0 0 of The SEO Framework! Use the_seo_framework()-get_post_meta_item( '_social_image_url' ) instead  I](https://user-images.githubusercontent.com/44450316/73814486-13bd5e00-4798-11ea-9e82-15e57b5d1d2b.JPG)

How do I fix this???  I tried looking at my SEO Framework setting but couldnt find a solution

Thanks for your help!!!

**Comment by sybrew** [comment]
Hello!

You shouldn't enable `WP_DEBUG` on production websites. It's meant for development; your visitors shouldn't see these messages. 😄 

In any case, the issue is that the site is using the Extension Manager v1.5.x plugin dating back to 2018. We've addressed this deprecation in Extension Manager v2.1.0, but that plugin is no longer hosted on WordPress.org, but via our servers instead.

See: https://theseoframework.com/extension-manager/

Please keep in mind that the Articles extension has been upgraded to be a paid extension in 2018, for various reasons extensively covered in [our blog](https://theseoframework.com/blog/all-for-nothing/).
