### ISSUE TITLE
Best way to translate the plugin in French

### ISSUE THREAD

**Issue by bonakor** [sybrew/the-seo-framework#508]
Hey,
What's the best way to translate TSF in French? Using the WP Plugin Repository (https://translate.wordpress.org/projects/wp-plugins/autodescription/) or doing it here?

**Comment by sybrew** [comment]
Thank you in advance for translating! 💯 

Yes, that'd be the place to do it. I recommend translating the Stable version.

Here's a [list of expectations for translating](https://make.wordpress.org/polyglots/handbook/translating/expectations/).

Please keep in mind that TSF uses Markdown language in some of its translatable texts. These tags should not be transformed when translating:
```md
`code`
*italics*
**bold**
[link title](link destination) // Do not add a space between the brackets
%s                             // arbitrary string
%d                             // arbitrary number
```

We're still looking for a French translation editor that can approve translations. Once you've proven to have a reputable translating record, the WordPress.org Polyglots team can make you a translation editor for TSF.

If you're stumbling upon difficulties when translating, feel free to [contact us directly](https://theseoframework.com/contact/) (or leave a comment here).

**Comment by bonakor** [comment]
Okay. Is it hard to find a French translation editor?

**Comment by sybrew** [comment]
It's hard to find an editor for any language since it's voluntary work. 😅 

It takes about 4 hours to translate the complete plugin, or about 45 minutes to approve other's work. Then it takes about 5 minutes every few updates or so when sentences arrive or change.

In exchange, you get a badge on your WordPress.org profile, an honorable mention on the translation page, and of course, a translated plugin for you and your friends. 😄

**Comment by bonakor** [comment]
Hello,
I'm almost done on the French Translation, but I'd need some infos for some strings I didn't find while using the plugin. 

**What are these string for?**
- Enable automated Schema.org output cache?
- It's automatically branded.
- The branding is duplicated.
- Not branded.
- It's manually branded.
- The authorized presence Schema.org output helps search engine users find ways to interact with this website. (this phrase, I just need to be sure about "the authorized presence"
- The buttons below are for primary %s selection.
- Authorized Presence Options
- It's not branded. Search engines may ignore your title.
- Output Authorized Presence?

**Just to be sure, when :**
- Page may not be archived. > means this page won't be listed in a archive page?
- The page may not be indexed, this may also discourage archiving. > means This page will be processed with a no-index tag, which may results in a "no-archive" instruction?
- Sitemap Query Limit > Who does the query?
-  Twitter Site  refers to the Link in the twitter bio ?

Thanks for your help :)

**Comment by sybrew** [comment]
That's amazing @bonakor, thank you!

### What are these string for?
- Enable automated Schema.org output cache?
   - You can ignore it. This string is gone since v4.0.5
- It's automatically branded.
   - Location: SEO Bar if you hover over the T. 
   - It means that the title has the blog name (brand name) appended automatically. `Page title - Brand name`
- The branding is duplicated.
   - Location: SEO Bar if you hover over the T. 
   - It means that the blog name is put twice or more in the title. `Page title - Brand name - Brand name`
- Not branded.
   - Location: SEO Bar if you hover over the T. 
   - It means there's no blog name in the title.
- It's manually branded.
   - Location: SEO Bar if you hover over the T. 
   - It means you've removed the blog name from the title, but added it back manually. `Brand name: page title`
- The authorized presence Schema.org output helps search engine users find ways to interact with this website. (this phrase, I just need to be sure about "the authorized presence"
   - Location: SEO Settings > Schema.org > Presence
   - The authorized presence are the verified business details of the site&mdash;who or what the site represents&mdash;, which can be displayed in a card on Google. Such as the organization name, type of organization, the logo, and connected social pages (deprecated).
- The buttons below are for primary %s selection.
   - Location: Post edit screen on WordPress 4.9 or below, or when using the classic editor. There, it's in a `[?]` inside the category selection meta box.
   - See **attachment 1** below.
- Authorized Presence Options
   - Location: SEO Settings > Schema.org > Presence
   - See my remarks above. I believe it should be "Options de Présence Autorisée"?
- It's not branded. Search engines may ignore your title.
   - Location: SEO Bar if you hover over the T. 
   - No blog name is found in the title. Google is notorious for adding it back anyway on their SERP, and therefore the title length calculations are rendered useless.
- Output Authorized Presence?
   - See my remarks above. I believe it should be "Sortie présence autorisée?"?

### Just to be sure
- Page may not be archived. > means this page won't be listed in an archive page?
   - No, we have another option for that. In this case, it means that search engines, and services like web.archive.org, are urged not to create a cached copy of the page. [Example archived page of theseoframework.com](http://web.archive.org/web/20180808035059/https://theseoframework.com/). This can come handy when dealing with time-sensitive data, like secured contact pages, or pricing pages.
- The page may not be indexed, this may also discourage archiving. > means This page will be processed with a no-index tag, which may results in a "no-archive" instruction?
    - Correct.
- Sitemap Query Limit > Who does the query?
   - TSF does the query 😄. It means how many posts TSF gets in a single request to the database, wherefrom it generates links. A large number may cause performance issues. A low number may cause some posts to be omitted from the sitemap.
-  Twitter Site > refers to the Link in the twitter bio ?
   - I think you mean this sentence? 
      - "When the following options are filled in, Twitter might link your Twitter Site or Author Profile when your post or page is shared."
   - Uh.... oops. It makes no sense what I put there 😅, I should change that. 
   - "Twitter Site" refers to the first option right below that, "Website Twitter Profile" (e.g. `@TheSEOFramework`). It means that Twitter may display a link to your business/website Twitter profile when someone shares a link. This statement is false, and I should change that sentence. For now, I believe it's only used for verification purposes... if at all.

## Attachments

### 1
![image](https://user-images.githubusercontent.com/7662236/76326373-d2652480-62e8-11ea-9b1a-03d7e90fbbc0.png)

**Comment by bonakor** [comment]
Okay, awesome. 

I think that at some point, I should find a way to be more precise when it's archive as archive page and archive as "search engine will create a cached copy of this page"

One last one, please. I'm unsure about:
"The positions in the "Meta Title Additions Location" setting for the homepage have been reversed, left to right, but the output has not been changed. " ?

**Comment by sybrew** [comment]
> I think that at some point, I should find a way to be more precise when it's archive as archive page and archive as "search engine will create a cached copy of this page"

We're mixing Google's and WordPress's terminology here, so that's a difficult task for all of us. ☹️  

- "The positions in the "Meta Title Additions Location" setting for the homepage have been reversed, left to right, but the output has not been changed. " ?
   - This is an info notice displayed for users upgrading to v4.0, where we switched the option to streamline the API. The option title is quoted: "Meta Title Additions Location". It means that, when you downgrade, `Homepage Title - Blog name` becomes `Blog name - Homepage title`.

I see you've uploaded the translations. Amazing work! I noticed some markdown issues, for which I'm going to suggest corrections. No worries :)

Can I submit a PTE (Project Translation Editor) request to Polyglots for you for fr_FR?

**Comment by sybrew** [comment]
OK, I'm done fixing the issues 👍 Once you're a PTE you can approve the translations, and I'll check again after you're done 😄 Let me know how you wish to move forward and feel free to shoot us an email at any time! Cheers!

**Comment by bonakor** [comment]
Okay, I've edited this string to follow your guidance.

> I noticed some markdown issues (links, code backticks), for which I'm going to suggest corrections. No worries :)

Sorry, I tried no to, but some may have went through :/

> I also noticed you translated "The SEO Framework" to "Le Framework SEO". "The SEO Framework" is a registered trademark, so I believe it should be left untranslated. I'll also forward suggestions to this.

Ooops, I just corrected this.

> Can I submit a PTE (Project Translation Editor) request to Polyglots for you for fr_FR?
Not yet. I'm just checking my translation in context on a dev website I have

**Comment by bonakor** [comment]
> OK, I'm done fixing the issues 👍 Once you're a PTE you can approve the translations, and I'll check again after you're done 😄 Let me know how you wish to move forward and feel free to shoot us an email at any time! Cheers!

Arg^^
I'll get the issues you fixed before uploading my new version

**Comment by bonakor** [comment]
Ok, it should be goog now.

**Comment by sybrew** [comment]
Thank you so much for the feedback!

Oops. I never registered these strings correctly, went unnoticed for years... great catch!
- Learn more about this card
- A title is generated for every page.
- Some titles may have HTML tags inserted by the author for styling.

_Note to self: Here's a regex to find missing translations:_
`(?<!_[_xen])\([^\(]+(?<=, 'autodescription').*?\)`

--------------

- "To improve performance, generated SEO output can be stored in the database as transient cache."
   - This string changed in TSF v4.0.5 (I removed the word SEO so to be all-inclusive). I believe you've used TSF v4.0.4 as your base for translations.

The other two strings have been removed in TSF v4.0.5, because Google fixed an indexing bug they were mentioning 😄 

-------------

About `Apply %1$s to %2$s?`

Is it possible to omit the gender/scope by removing the article in French? 
e.g. "Apply X to the archive" -> "Apply X to archives".

It's not as neat, but it's valid 😅 The settings are automatically generated based on registered post types, so I don't have a lot of freedom here.

**Comment by bonakor** [comment]
> Is it possible to omit the gender/scope by removing the article in French?
> e.g. "Apply X to the archive" -> "Apply X to archives".
Well, sadly not because in French, we have this construction:
Appliquer (for apply) aux Archives (when it's plural)
Appliquer à l'archive (when it's singular)

I have an idea but are you using those strings only in this case (https://1drv.ms/u/s!Au0MdBEI3YTDl4xuQbQymFJoXVC_Fw?e=dQJJvp) ?
- Author pages
- Archives par étiquette
- Category archives
- Date archives
- Search pages
- Posts
- Pages 
- the entire site

**Comment by sybrew** [comment]
These are the registered instances. We'll automate the archives array in v4.1.0 (automatic detection of supported taxonomies), as part of #20.

https://github.com/sybrew/the-seo-framework/blob/3704c3a363b741a4bebdf55174d005063f891a81/inc/views/admin/metaboxes/robots-metabox.php#L19-L28

I made an internal note that we should address the sentences as best as we can anticipate. We'll probably split the translatable parts from singular and plural.

For now, I think it's best to assume everything's plural. I'll make an exception for "for the entire site" in an upcoming update.

**Comment by sybrew** [comment]
Here's the PTE request: https://make.wordpress.org/polyglots/2020/04/18/hello-polyglots-i-am-the-566/

Better late than never 😃. It's been hectic. 

Thank you so much for your contributions, @bonakor!

**Comment by bonakor** [comment]
Yay! I'm working with the locale team to speed up validation

**Comment by sybrew** [comment]
Thank you for providing over [1000 translations](https://translate.wordpress.org/locale/fr/default/wp-plugins/autodescription/)!
