### ISSUE TITLE
New title length for Googles SERPS

### ISSUE THREAD

**Issue by dosimotion** [sybrew/the-seo-framework#518]
Google recently slightly changed the size of the titel showed in the SERPS.
Thaty why my Company (SEO-Tool Seobility) has corrected the pixel-Calculation for titles.

See https://www.seobility.net/en/serp-snippet-generator/

Would you also correct the needed values in TSF?

**Comment by sybrew** [comment]
Thanks for sharing your findings! 

I'm afraid I couldn't verify this change in the Netherlands, maybe it still has to roll out globally? 
Could you share the research that supports this?

Please note that we shot ourselves in the foot with [the description reworks earlier](https://github.com/sybrew/the-seo-framework/issues/318). Since then, I'm a bit hesitant to implement such changes as they might get reverted. That'd ultimately be a waste of time for our users, as they then have to change their titles again.

**Comment by callaloo** [comment]
> Please note that we shot ourselves in the foot with the description reworks earlier. Since then, I'm a bit hesitant to implement such changes as they might get reverted.
I remember this same thing happened when I used Yoast a few months before switching to TSF. Upon switching, I had to go to several posts to rework the meta description from 320 characters to the recommended ones in TSF. Very frustrating exercise.

**Comment by sybrew** [comment]
This could've been transient regional testing. Closing as invalid.
