### ISSUE TITLE
php 7.4 implode() warnings in post/page SEO column

### ISSUE THREAD

**Issue by eSaner** [sybrew/the-seo-framework#533]
**Describe the bug**
With php 7.4 the following warning is in the SEO column of posts/pages.

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /home/user/Sites/test.com/site/web/app/plugins/the-seo-framework/inc/classes/sanitize.class.php on line 1525

**How to reproduce the bug**
1. Go to Posts
2. See errors in the SEO column

**Expected behavior**
No warnings.

**Additional context**
Switching the order of the implode() parameters makes the warnings go away.

TSF 4.0.7
WP 5.4.2
Roots Bedrock

**Comment by sybrew** [comment]
Hello!

I think you're using TSF 3.2.4 or earlier. 
https://github.com/sybrew/the-seo-framework/blob/123d18c25fae21cc1ef11d06bb6b1bd85278174c/inc/classes/sanitize.class.php#L1525

This issue was resolved in TSF v4.0.3: https://github.com/sybrew/the-seo-framework/commit/3be5ae50db2c71973a638b50c313f09b7fa47ac4#diff-5048117aa6e9efbc5d23b1ade5e6562c.

If the plugin didn't update correctly, please delete it and re-upload the latest version. The plugin won't remove your data on deletion.
- w.org: https://downloads.wordpress.org/plugin/autodescription.4.0.7.zip
- GitHub: https://github.com/sybrew/the-seo-framework/releases/tag/4.0.7
- Packagist: https://packagist.org/packages/sybrew/the-seo-framework#4.0.7

**Comment by eSaner** [comment]
Yes, you are correct, sorry! Upgraded and all is fine in WordPress, though lots of composer deprecation warnings in the terminal about classes not being psr-4 compliant.

**Comment by sybrew** [comment]
I believe I should remove the PSR-4 autoloader from the schema. TSF has a custom one (via `spl_autoload()`) well integrated, which loads conditionally. All you need is to load its base plugin file (`autodescription.php`).

That said, I've never used WP + Composer ([David took the words out of my mouth](https://wptavern.com/i-love-composer-i-love-wordpress-but-i-object-to-a-marriage)), so I'm not sure if there are any repercussions to such a change.

**Comment by eSaner** [comment]
To each their own. I love Composer with WP. Wouldn't want to do it any other way. Perhaps your autoloader can co-exist with PSR-4 without too much modification? I appreciate your work. Cheers.
