### ISSUE TITLE
sitemap generate by cron or by wp-cli cron job (More thank 300k posts)

### ISSUE THREAD

**Issue by majestica** [sybrew/the-seo-framework#539]
Hi, I decided to try your plugin (it really cool), and it seems to me that mine began to work for a very long time (more than a minute and it is simply impossible to work like that) when saving, deleting, adding posts, as I understand it, the sitemap is rebuilt on the fly, I have about 300k records in the posts table , and more than 1 million records in the post_meta ... please tell me the solution, if it were possible to update the map by the crown or through wp cli by cron would be very cool, and getting a map from the cache would also be very cool. thanks for the help

**Comment by sybrew** [comment]
Hello!

I think you're following up on this issue: #460? I've learned some new things since then. Let's go over it.

When a sitemap takes a very long time to generate, search engines will forgo crawling it. They'll index it at a later time, when its file is quicker to respond, though. See https://support.google.com/webmasters/answer/156184.

Various tests have been conducted that postulate you should only show posts in the sitemap that aren't already in Google's index&mdash;this allows for the fastest indexing rate. See https://ohgm.co.uk/an-alternative-approach-to-xml-sitemaps/.

It is, evidently, also how TSF's sitemap is set up: It sorts through the posts in a fashion, where recently published and updated posts are shown on top. So, if you lower the number of items displayed in the sitemap, not only will it generate faster (or instantly), but it'll also help Google index your pages more quickly.

Nevertheless, we should consider implementing a native solution around this--where the sitemap is generated in the background before search engines touch it.

Until then, a cronjob hook will work--but only if you enable TSF's pinging via cron. Keep in mind that when we ping search engines, they crawl it instantly... So, you may want to implement a custom script that generates the sitemap before pinging, like this snippet below.

```php
add_filter( 'tsf_sitemap_cron_hook', function() {
	$sitemap_url = \The_SEO_Framework\Bridges\Sitemap::get_instance()->get_expected_sitemap_endpoint_url( 'base' );
	wp_remote_request( $sitemap_url, [ 'timeout' => 1 ] ); // Request the sitemap, timeout ASAP.
	sleep( 30 ); // Wait for it to complete generating, before doing anything else, like pinging the search engines. Adjust number to needs.
}, -10 ); // Load super early in the cron.
```

I think we can vastly speed up sitemap generation once this Trac ticket is resolved: https://core.trac.wordpress.org/ticket/50567.

Alongside that, we're also considering adding pagination to the sitemap. https://github.com/sybrew/the-seo-framework/issues/31#issuecomment-467852922

**Comment by majestica** [comment]
> I think you're following up on this issue: #460? I've learned some new things since then. Let's go over it.

> I think you're following up on this issue: #460? I've learned some new things since then. Let's go over it.
yes it is true, exactly a year ago I had the same problems only now everything got worse as there were more posts ..

Thank you, i will try use filter and i hope this help

**Comment by sybrew** [comment]
In 4.1.2 we're going to add a hook that allows you to generate the sitemap easily without requiring cURL or wget, but simply a API call (which can be extended to CLI if you so desire).

**Comment by sybrew** [comment]
In 4.1.2, we're not only going to add that hook, but also provide an option that allows prerendering via cron.

This is combined with a sitemap lock to prevent bombarding the sitemap's rendering engine. We're also implementing delayed pings that fire only when the sitemap is unlocked. 

These additions should create an amazing feature set for sites with huge sitemaps, but also for sites with restrained processing power.
