### ISSUE TITLE
Sitemap issue

### ISSUE THREAD

**Issue by askel45** [sybrew/the-seo-framework#547]
Hi. I use www on my site URL. When I type the sitemap URL without www, it does not show and results in a blank page. It only shows when I add www to the URL.

**Comment by sybrew** [comment]
Hello!

That's because the XSL file may not be outputted across (sub)-domains for security reasons.
![image](https://user-images.githubusercontent.com/7662236/90202811-0cc67680-dddf-11ea-97b5-adce8c0c3f3a.png)

The sitemap still works, but it's merely not painted for humans--robots should deal with it just fine. Inspect the source of the seemingly broken sitemap, and you should see all machine-readable URLs.

The XSL file will always work on the sub-domain you've entered at "General > Site Address (URL)". It's what we use to generate all your canonical URLs, and also the link to the sitemap's stylesheet. In your case, that'd be with the `www.`-subdomain.

**Comment by askel45** [comment]
Okay. I want to create a cron job to create warm cache from the sitemap. It seems the cron is not working with the www version of the URL. So it is okay if I strip the www from the cron?

**Comment by sybrew** [comment]
Both www and non-www should call the same sitemap. The sitemap only differentiates its cache using the blog ID and the locale.

So, it shouldn't matter which one you call 😄 

If you check the source of the sitemap, you can read the generation time at the top in an XML comment, and whether it was served from cache at the bottom.

As for warming the cache, see: https://github.com/sybrew/the-seo-framework/issues/540
I explained why doing it yourself isn't the best option, but there's a snippet present, here: https://github.com/sybrew/the-seo-framework/issues/539#issuecomment-663809441

Essentially:
> [...] Keep in mind that when we ping search engines, they crawl it instantly... So, you may want to implement a custom script that generates the sitemap before pinging, [...]
