### ISSUE TITLE
Add filter for lastmod date for the homepage (as blog) in sitemap.xml

### ISSUE THREAD

**Issue by ram108** [sybrew/the-seo-framework#551]
If a custom page is used for the main page of the site, then the date of the page change in the sitemap.xml is considered the date of the exact page change.

This leads to the fact that the main page may have the lastmod date years ago, which is not true at all.

The title page can contain display of recent posts or dynamic content, so the modification date of the title page should be the latest modification date of any post.

For example, our site is updated daily, but I found that in the sitemap, the date of the title page change is 2017! Which is completely wrong.

See screenshot: https://ibb.co/G35CbCz

**Comment by sybrew** [comment]
Hello!

We read the `post_modified_gmt` time for changes on the homepage. WordPress influences this.

When the homepage is a blog (according to WordPress, not your theme/plugin), we'll also test for the latest public post's `post_date_gmt` time (publishing time, not modified), and see which one of the two is later.

If you're working with a custom solution to update the homepage, then you may want that also to influence the `post_modified_gmt` time. 

Alternatively, you can manually update that time via WordPress's interface: Hit "Save/Update/Publish" via quick-edit or the page's edit screen.

**Comment by ram108** [comment]
Sorry, I did not understand what to do? Do I need to republish homepage manually every time to update homepage change time?

Here are examples of other sites that use diffrent themes and plugin combinations. Every site have wrong homepage date.

Screenshots:
https://ibb.co/3FdK25R
https://ibb.co/Fs7tqt8

The homepage date shoul be always the last publish/update of any post in the site. But not the date of several years ago. I'm just terrified that search engines might think of this.

**Comment by sybrew** [comment]
Hello again!

The dates seem correct to me.

For saisspeaks, see the published date of the latest post:
![image](https://user-images.githubusercontent.com/7662236/91228365-69535b00-e728-11ea-9519-fb1999a4642b.png)

Astroshop's front page is a page. So, that date's also correct (it's taken from the home page's page itself). You may need to invoke an update for that page manually if you wish to update the timestamp.

> The homepage date should be always the last publish/update of any post in the site

We only use the latest published date--this is also how WordPress orders things.

> I'm just terrified that search engines might think of this.

They don't think much of it. Search engines crawl pages periodically, regardless of the timestamp, and regardless of whether you have a sitemap or not.

Some even ignore that value completely in favor of asserting the dates autonomously. They may add that timestamp to the SERP snippet, but that's the "worst" thing that can happen. If you believe it's inaccurate, then you can omit it from the sitemap:

![image](https://user-images.githubusercontent.com/7662236/91228759-1201ba80-e729-11ea-96b1-e4c7f211c417.png)

For small sites (fewer than 500 posts), disabling this option should not have any noticeable impact.

**Comment by ram108** [comment]
It seems to me that there was a misunderstanding. Are you using the page creation date or update date?

If the date of creation, then everything is in order. If the date of the update, then it is clearly worth working on.

The meaning of these dates is to show the search engine that a particular page has been changed. In this case, the date displayed in the current version of the plugin absolutely does not correspond to the context of the main page.

I don't know about Google, but Yandex is analyzing update dates very carefully. If the page has not been updated for a long time, then it is pessimized in the search.

Therefore, such a wrong date can have serious consequences for the SEO.

This is a bug, not a feature.

![s](https://user-images.githubusercontent.com/2060570/91304398-17571780-e7b2-11ea-8740-997706d33f1d.PNG)

**Comment by ram108** [comment]
> For saisspeaks, see the published date of the latest post

Yes, but plese see update date of the posts. They are totally diffrent. So, is that an update date of creation date?

**Comment by sybrew** [comment]
For the blog page (homepage as blog), we use the blog page's last updated page, or the latest post's creation date--whichever is at a later time. From what I can see from here, the dates are correct.

**Comment by ram108** [comment]
> the blog page's last updated page

OK. **Last update date**. Understood and agree.

> the latest post's creation date
??? **Create date.** Why not to use here last update date as above?

And even so, we won't get the correct date.

Let's assume a standard situation. The installed theme uses a custom page to display the blog posts on the home page. The homepage was created a year ago.

BUT! The blog is updated every day and the home page contains new content every day.

What is the date of the last update of the main page? A year ago, or is it according to the last blog update? 

Is the content of homepage is the same as a year ago? What will you unswer to the search engine?


PS. Sorry for my persistence. I am a senior web programmer myself with 20 years of experience. And I think your plugin is one of the best. Therefore, I think that it is easily possible to make the correct calculation of the time of changing the main page, corresponding to its real content, and not engage in theoretical reflections on this matter.

**Comment by sybrew** [comment]
> Why not to use here last update date as above?

Because WordPress doesn't order posts on your page based on their last-updated time. If you update a post on page 10, it won't modify the homepage. So, we do not update that timestamp.

To reiterate, if you believe this is obstructing, then please disable the feature. Yandex can work without the sitemap's `lastmod` output--it's not a required element.

From https://yandex.com/support/webmaster/controlling-robot/sitemap.html, Yandex implies a sitemap is optional (and that `lastmod` is optional). Especially for smaller websites with a good heuristical architecture. Your website complies fully with that.

> Let's assume...

I always assume (it's why the plugin is nearly bug-free), and I resolve edge cases when they're easy to resolve and don't cause problems down the line. For instance, if you change the theme, should we assume all pages are updated? 

This is where it gets misty: who, in the end, are we helping, and what are we resolving?

It boils down to that search engines use algorithms to test for changes automatically; comparing strings is easy. So, we don't have to. Again, `lastmod` is optional and we've seen cases where it's ignored. Search engines are smarter than most people think.

Please keep in mind that for every feature I bring to the table, like a toggle that picks the last modded time, I'll need to maintain, document, and help with support for it. Users must also be taught to understand such a feature, which eats up their time. A 5-minute feature can end up eating hundreds of hours. For something so obscure and optional, I don't believe the tradeoff is worth it.

**Comment by ram108** [comment]
I understood. Thanks again for the great and free plugin, and for your time.

Can you advise me if there is a hook or action that can help me to change the output of the sitemap.xml? I will manually change this date so nobody else will be disturbed.

**Comment by sybrew** [comment]
I'm afraid that value is hard-coded and bound to the post read directly from the database:
https://github.com/sybrew/the-seo-framework/blob/9ab6980882d71434a3023afd316fd8c5cd889356/inc/classes/builders/sitemap-base.class.php#L388-L392

Adding a filter there would add about 120 microseconds per post. When users have 50&nbsp;000 posts, that'll add 6&nbsp;000&nbsp;000 microseconds (6&nbsp;seconds!) just to support a case where you could also simply disable the `lastmod` output without ramifications.

Since we also bypass WordPress's post sanitization filters during the sitemap request (for performance), there's no way to modify this value, other than modifying it in the database. You can learn more about the implications and pitfalls we've encountered in this [Core Trac ticket](https://core.trac.wordpress.org/ticket/50567).

So, the only solution is to modify the post's date by adjusting the value via the post-edit screen (this affects the front-end, too). At the top-right of the post, under "Status & visibility", you can select the date:
![image](https://user-images.githubusercontent.com/7662236/91513506-ca279280-e8e4-11ea-9c05-dfede8ce3ec0.png)

**Comment by ram108** [comment]
Clear. So the best option is to programmatically update the lastmod time of the page itself, then the plugin will pick up these data automatically. Thanks for the good advice.

In terms of the plugin, I think this is about the main page and blog page, not all 50,000 posts. There will not be a big load here to correctly calculate the date.

**Comment by sybrew** [comment]
> In terms of the plugin, I think this is about the main page and blog page, not all 50,000 posts. There will not be a big load here to correctly calculate the date.

You're right. But, we use the same code to create those URL entries. I don't think it's the best approach to create a dispersion in methodology that practically achieves the same--where one has a filter, and the rest don't. In the end, I'll have to maintain that code just for one known edge-case, potentially creating bugs.

Again, it's a moot discussion: Neither Yandex nor Google care. Please disable the output if it's not working for you, or replace the sitemap with one that offers you more control. If you're up for it, you can even replace the complete sitemap generator with the `the_seo_framework_sitemap_endpoint_list` -> `['base']['callback']` filter.

**Comment by sybrew** [comment]
In v4.1.1 I'm going to add a filter that allows you to adjust the `lastmod` value for the homepage when it's a blog.
We might deprecate this filter later to make it compatible with other values asserted for SEO meta output.

**Comment by ram108** [comment]
Thank you so much! I'm very glad to hear that. Your plugin is the best, I have been using it on all sites for quite some time now.

**Comment by sybrew** [comment]
Example:

```php
add_filter( 'the_seo_framework_sitemap_blog_lastmod', function( $lastmod = '0000-00-00 00:00:00' ) {

	// Expects GMT date! Please make this timestamp relational--don't update it to an arbitrary time (don't fool Google!).
	$lastmod = gmdate( 'Y-m-d H:i:s', strtotime( '2020-09-02 12:00:00 GMT' ) );

	return $lastmod;
} );
```
