### ISSUE TITLE
get_og_type() should allow Post ID parameter

### ISSUE THREAD

**Issue by henrikwirth** [sybrew/the-seo-framework#558]
Hi guys. I'm working on a WPGraphQL extension for a client right now and found that there is no option to get the open graph type by the post id.

If you would add this: 
```php
public function get_og_type($post_id = '') {

    static $type = null;

    if ( isset( $type ) )
        return $type;

    /**
     * @since 2.3.0
     * @since 2.7.0 Added output within filter.
     * @param string $type The OG type.
     * @param int    $id   The page/term/object ID.
     */
    return $type = (string) \apply_filters_ref_array(
        'the_seo_framework_ogtype_output',
        [
            $this->generate_og_type($post_id),
            $this->get_the_real_ID(),
        ]
    );
}


public function generate_og_type($post_id = '') {

    if ( $this->is_product() ) {
        $type = 'product';
    } elseif ( $this->is_single($post_id) && $this->get_image_from_cache() ) {
        $type = 'article';
    } elseif ( $this->is_author() ) {
        $type = 'profile';
    } else {
        $type = $post_id;
    }

    return $type;
}

```

`is_single` already accepts post ids, so only `get_og_type` and `generate_og_type` would need to get a parameter passed down.

Would be great, if this could make it into a release, so I don't have to customize it for the customer.

Thanks for your work.

**Comment by sybrew** [comment]
Thus far, the Canonical URL, Description, Image, and Title generators can generate data via input arguments. Since we never had an internal need for the other generators to have this capability, it got shoved aside for "maybe later." Nevertheless, I understand the requirement.

See (related, duplicated?) proposal: #445--which covers the request in this particular issue as well.

I think that TSF v5.0 or v5.1 will do well with this implementation, since we'll then have generators everywhere. I'll mark #445 for v5.0 already, so that we can get this moving.

I'm marking this (good first) request as a duplicate. Feel free to follow up here if you think it's erroneous; otherwise, please continue at #445. Cheers!
