### ISSUE TITLE
Linking to pages that are excluded from search

### ISSUE THREAD

**Issue by wpjames** [sybrew/the-seo-framework#571]
When I enable the option "Exclude this page from all search queries on this site", I am not able to create a link to that page from another page using the Gutenberg editor.

Is it possible to make the search result exclusion only apply to users not logged in so those pages can still be linked to from other pages?

**Comment by sybrew** [comment]
It's interesting to see how this affects Gutenberg; the filter we apply should only affect the front-end, where `is_admin()` returns `false`.
It's also interesting that they use a WP Query search query, instead of something more specific.

No, we should not apply a bias to logged-in vs. logged-out; that'd cause discrepancy and confusion.

**Comment by sybrew** [comment]
[Similar report](https://wordpress.org/support/topic/cannot-set-an-internal-link-in-gutenberg-to-pages-excluded-from-search/). I feel like this is a bug in Gutenberg, not TSF.

**Comment by sybrew** [comment]
Perhaps we can easily resolve it by checking for rest-requests before running the filter. This is a guess that requires investigation.
