### ISSUE TITLE
Option to Show Title and Description as Columns in Admin Overview Tables

### ISSUE THREAD

**Issue by black-eye** [sybrew/the-seo-framework#576]
It would be nice to have an option to add extra columns for Title and Description to the overview tables. 

While it's definitely not a case for a daily use, since those fields require a lot of space, it's really useful for the quick check, wheather the fields are filled in and what their values are. 

This feature I really miss, as I use(d) it both in SEOPress and Yoast quite a lot.

Thanks for consideration.

**Comment by sybrew** [comment]
Hello!

Thank you for your suggestion. This feature was shoved off the table many years ago already, in pursuit of something more usable for everyone.

First, TSF already shows title and description assessments via the SEO Bar -- hover over them to learn more.
At a glance: if there's no G with the T/D, then it means you've manually inputted a title or description.

And, if you wish to view the title/description quickly, you can do so already via Quick-Edit. 
Hover over any post, and the Quick-Edit option should present itself. There, you'll find capable editors for the title and description.

From: https://theseoframework.com/blog/an-introduction-to-a-thousand-changes/
> Whereas others resort to out-of-brand editing tools, we implemented this right into WordPress’[s] very own quick and bulk-editing interface. For those familiar with this mechanism in WordPress, let’s just say we sprinkled some magic dust over the code and made it work seamlessly.

The issue: https://github.com/sybrew/the-seo-framework/issues/464

The out-of-spec feature Yoast and SEOPress have implemented cause bounding-box-overflowing issues on most 13" (and smaller) laptop-screens &mdash; also on larger screens with plugins like WooCommerce and bbPress &mdash; because WordPress's Post-table-overview is built using the 'bounding-box-unaware' CSS2.

**Comment by black-eye** [comment]
OK fair enough. In fact I was expecting similar explanation and tried to search it between the closed issues, but haven't found any. 

I'm aware of the quick edit option as well as of SEO bar, but somehow I feel that the extra column is the most clear option for a quick check. Even though I use it always only temporarily because - as you mentioned - it can cause huge issues when there are menu columns involved.

Never mind, no big deal ;-)
