### ISSUE TITLE
Export and Import Title and Description 

### ISSUE THREAD

**Issue by roteixeira1986** [sybrew/the-seo-framework#587]
Our client has a website with content in 4 languages. Not all pages have content in all those 4 languages. It would be nice if we could export the titles and descriptions for only a section of the website (let's say a page category), not the whole thing, so we could translate the titles and them bulk import them.

**Comment by sybrew** [comment]
TSF has no export/import module.

Since TSF uses the default WordPress Post/Term Meta APIs, its metadata can be exported together with everything else when you transport a post. The post-exporter you're using should be able to discern the languages.

Here you can find what [Post Meta TSF stores](https://kb.theseoframework.com/kb/data-stored-in-your-database/#tsf-post).
