### ISSUE TITLE
Automatically Truncate Long Titles

### ISSUE THREAD

**Issue by laloneo** [sybrew/the-seo-framework#628]
Hello,

We managed to have about 1,000 posts with long titles. Is there a custom function we can use to automatically truncate the titles to an acceptable limit? 

Maybe the logic should work like: 

if no. of characters > value then
   truncate...
end if

**Comment by laloneo** [comment]
If there is no harm and search engines will change the title, then I guess its fine? It's just that the SEO Framework plugin marks long titles with red color, so I presumed that would be a problem..

**Comment by sybrew** [comment]
It is a problem when you want search engines to display exactly your preferred title because when we mark it red, it almost definitely won't. But otherwise, it's OK -- especially for generated or quickly pushed content.

To learn more, see https://www.searchenginejournal.com/google-title-tag-length/400682/.
