### ISSUE TITLE
More inpost options for Open Graph/Twitter.

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#64]
I am coming from Yoast (surprisingly) and I relied on this function quite a bit.

1. Is there a way to fill in the meta-data for sharing on social networks?
2. If not, is this function planned? Will it be core, or extension? Or it already exists, but only in premium?

![capture](https://cloud.githubusercontent.com/assets/5657511/21933671/981806b8-d9a6-11e6-9741-afe826b8a7c4.PNG)

I was not able to find the answer anywhere else on your website or here in issues, although you are mentioning social networks and meta properties a lot in your blog posts. Thanks for clarification!

**Comment by sybrew** [comment]
Hi @LeBaux,

In 2.8.0 you can select your special Social Image (1), which will automatically be converted to Facebook's best practices, including suggested cropping dimensions (2): 
![image](https://cloud.githubusercontent.com/assets/7662236/21935787/1a44f5e4-d9af-11e6-9979-5e9f141c8ae6.png)
![image](https://cloud.githubusercontent.com/assets/7662236/21935844/545f5350-d9af-11e6-8faa-1e6494ff2bdb.png)
 
The description will be automatically generated, where it will be nearly trimmed to 155 characters for Search Engines, and 200 characters for Open Graph (Facebook). If you use the WordPress provided Excerpt field you'd be able to get a more semantic structure of these output data.
However, you're able to also insert a custom description. This input will then yield exactly as-is and will be the same for Search Engines, Open Graph and Twitter alike.

If you wish to gain more granular control, an extension that allows you to do so is planned.
That extension will require TSF 2.9.0 (planned Feb/March... or later) as it requires tabular control in the post SEO settings.

We're just starting undergoing a transition from being an all-in-one SEO activate-and-go plugin to the ultimate tool for everyone's needs 😄. Stay tuned!

**Comment by sybrew** [comment]
Related: #62

**Comment by sybrew** [comment]
The additional options might be moved into the main plugin rather than an extension. It might be too crowded for some people, however.

It should also listen to the OG/Twitter settings (i.e. are they activated?).
When they're deactivated, the fields should remain dormant (`type=hidden`) to prevent loss of data.

**Comment by useyourblinker** [comment]
Dear sybrew,

Which sharing sizes are you using? Facebook's recommended sharing sizes are (sometimes) NOT actually the ideal sharing sizes that people should post on their pages.

Example: Facebook recommends 1200x630 in a certain instance for a cover photo, but only actually displays 828x312 (out of an image they might recommend making 828x460).

I think it would be beneficial to have a checkbox that can enable OR disable cropping dimensions.

One more reason to maybe make that _optional_ (in my opinion) is that some pages might be intended to be shared to be optimally viewed on Mobile (Facebook app/mobile site) instead of Desktop. And those 'best practices' resolutions are not only different, but not listed correctly.

One more reason that I might want to NOT have the image cropped to 'suggested dimensions' (as noted at the beginning):

On Desktop, on a 1080p monitor, full image share size only ends up at 476x249. If you share with an image that is 1200x630 or 600x315 (suggested sizes), Facebook is going to crop AND compress (badly) your image. If I have my og:image as a 476x249 size and keep the compression and size reasonable, Facebook will not butcher the image so badly.

For this reason, I would prefer to NOT have Facebook share images be cropped -- or at least, see a 'Crop' checkbox, or an og height and og width custom area, if I want.

Just throwing some input in here.

Thanks for everything you do!

**Comment by sybrew** [comment]
Hi @useyourblinker 

Facebook sets those guidelines as per reasoning for "what's to expect". 
It's up to Facebook to adhere to those guidelines and adjust them when needed. We simply follow them.

Sharing images **is not equal to** sharing links.
The Open Graph standard is for sharing links. 
When you share images, another process follows, and it doesn't involve using Open Graph.

----

#### For Open Graph images, here's what you should know:
https://developers.facebook.com/docs/sharing/best-practices#images
The output is per ratio 1200x630 (≈ 1.905:1 ≈ [US Film format](https://en.wikipedia.org/wiki/Widescreen#Film)).

In 2.9.3, the forced cropping starts at 4096x4096.
See https://github.com/sybrew/the-seo-framework/issues/139 and https://dev.twitter.com/cards/types/summary-large-image for more information.

The cropping was smaller (1500x1500) because some social sites were (back in the old days) saving bandwidth.

So, the sharing sizes TSF uses are:
`<= 2.9.2 : 1500x1500 max`
`>= 2.9.3 : 4096x4096 max`

---
#### This is what happens in your dashboard:

*This is a 2.9.3 example, which allows up to 4K, rather than 1500x1500, but it's still the same principle.*

The aspect ratio (1.905:1) will always be maintained when the cropping screen opens, no matter what size. As seen by the dotted lines below:

![image](https://user-images.githubusercontent.com/7662236/27004832-ed20008c-4e10-11e7-839f-8042644892d6.png)

When you crop the image, you will see this:

![image](https://user-images.githubusercontent.com/7662236/27004840-29b35346-4e11-11e7-9479-38d2a243758b.png)

It's almost perfect, I sense there's a minuscule bug in WordPress' cropper, but it's at worst minimally incoherent for the developer (i.e. me).
`4096x2155 => 4096/2155 ≈ 1.901 ≈ 1.905:1 ≈> 1200x630`

---
#### Now, about Facebook's image quality.

It's good enough, and it's up to them to improve it, and it's up to them for optimizing it for different screens.
When they will support 2x pixel ratio or lossless-esque image compression, then we'll be there supporting them with the 2.9.3 update.

Until then, we can't and shouldn't influence it nor should we guess what's best. That's completely up to Facebook. When Facebook decides to improve the quality, they will.
Let's just adhere to the guidelines as best as we can, chasing anything otherwise is a call for technical debt and time consumption. Let's stay ahead of time.

When sharing a 4096x2151 Open Graph PNG image, it looks perfectly fine (see image below). 
*Note, Windows' Snipping Tool and GitHub have put another compression upon it. I can't spot blurriness!*

![image](https://user-images.githubusercontent.com/7662236/27004901-83357132-4e12-11e7-8b8f-afac54cb4b3a.png)

**Comment by sybrew** [comment]
From #178 

>An option to remove the additions (e.g. blog name) from the post title tag used for social sharing would be helpful.
>
> Facebook as an example includes the domain below the description so including blog name in the title doesn't add much value.

**Comment by TK42DAN** [comment]
You can add me to the list of folks who would love more granular control over social sharing settings, etc. As a novice, I do appreciate the way plugins like Yoast make it so clear what I'm doing in this regard. We use Facebook and Pinterest primarily, and occasionally Twitter, for what it's worth. I don't know enough about this stuff to offer anything more helpful than, "Try to keep it straight forward for novices like me." :) Thanks!

**Comment by sybrew** [comment]
From [karex' suggestion](https://wordpress.org/support/topic/multiple-ogauthor-tags/):

Also add multiple `og:author` tags. Where the main post-author is auto-selected (and can't be deselected).

I think the best way to implement this is like I did with Local SEO's cuisine selection:
![image](https://user-images.githubusercontent.com/7662236/34031032-d31e6f96-e16f-11e7-9753-8adee86c4ba6.png)

**Comment by karex** [comment]
Thanks for landing my idea here! This implementation might be good for some, although I think those in need for multiple authors might already have some solution for that in place, so my idea was just to make it possible to have multiple og:author tags by a slight change in the related [render function](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/render.class.php#L676). But if the latter comes with the former, then this is cool. :)

**Comment by sybrew** [comment]
For anyone looking for a temporary solution while this is on its way, you can do this through ACF.

See https://github.com/sybrew/the-seo-framework/issues/247#issuecomment-354267725 for details.

**Comment by sybrew** [comment]
This will be in the main plugin, as it's now required due to the description changes.

**Comment by sybrew** [comment]
Candidate for 3.0.4. This might be pushed to 3.1.0 regardless, depending on the difficulty of the 3.0.4 release.

**Comment by sybrew** [comment]
Regarding https://github.com/sybrew/the-seo-framework/issues/64#issuecomment-321671043, the additions will be removed by default on input.

**Comment by sybrew** [comment]
Automated social descriptions will be increased to 300 from 155 characters. 
This is (luckily...) the same as proposed in #231; so, no code reflow is required (yet).
