### ISSUE TITLE
Typo: "Note: rhe description " on Settings > Homepage > Meta Description

### ISSUE THREAD

**Issue by oldrup** [sybrew/the-seo-framework#657]
Huge find! 🕵️‍♂️😁

![image](https://github.com/sybrew/the-seo-framework/assets/17141205/61b1da5a-168a-46d2-bc45-00004507a2a4)

**Comment by sybrew** [comment]
Thank you for the report, Bjarne!

It's actually a long-standing [typo in the translation for UK English](https://translate.wordpress.org/projects/wp-plugins/autodescription/stable/en-gb/default/?filters%5Boriginal_id%5D=6740514&filters%5Bstatus%5D=either&filters%5Btranslation_id%5D=78962737) 😅

I just suggested the translators a fix (and then another one because I also made a typo...)
