### ISSUE TITLE
Outline difference between premium and free

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#66]
_This is more of discussion piece on onboarding & marketing, rather then code issue but I think github is able to facilitate discussion on this front. As a bonus, you are not fragmenting discussion on more platforms - but if you want I can repost this on wordpress plugin discussion site._

**I am currently very fresh user of TSF, so I am encountering some questions that other transitioning webmasters might face. Currently the biggest question is what is difference between premium and free - specially since I can activate extension manager for free. Are all modules there, or are premium hidden? Is there dev roadmap for plugin and extensions?**

You answered some of these questions to some extend [here](https://wordpress.org/support/topic/not-all-topics-are-allowed-here-read-me-before-posting/) and [here](
https://wordpress.org/support/topic/per-site-subscription/), but I think you should consider adding FAQ to both your website and wordpress plugin directory and even maybe here on github in project description. Thanks for your time!

**Comment by sybrew** [comment]
Hi @LeBaux,

That's quite a broad question, and I can't give you a complete answer: because I don't have a complete answer. Nevertheless, I'll try my best to make things clear.

## The fine line between Free and Premium
**Premium**: The software requires an API connection in order to (partially) function. This allows for awesome and yet unheard of features.
**Free**: Almost everything else I publish.

#### Are there any other differences?
Well, from the user's perspective: not really.
You can view all available extensions right from your dashboard, both free and premium.

The premium extensions will generally also receive more love (like visual effects, extended AJAX support, etc.), as people pay for it, but that still doesn't make a big difference. You can already see these efforts in the "Plugin" and its admin interface. It's written according to the [Flexible Box spec](https://www.w3.org/TR/css-flexbox-1/) (almost all browsers will fail) with the help of [Browserstack](https://www.browserstack.com/), just try resizing your window 😄, on any browser (all browsers will pass).

What does make a big difference is that the Monitor extension, for example, took me 3 months to set up, and it's still far from finished. The server software of which is 18000 lines and counting, it requires a database, hardened security, exception handling, parsing of data, etc.

Whereas the Title Fix was a single all-nighter to get built.
The premium extensions are essentially written with completely different environments at hand.

These features, at their current state, aren't worth the full price. That's why there's an "Early Bird" initiative. I hope to make this difference more clear as the project grows.

Although, in perspective, the Extension Manager alone could've bought me a Tesla model S (P100D) if my time building it was spent at an IT company. Nevertheless, I hope people don't take that all for granted 😄.

### All code is open source
For both premium and free extensions. This was a requirement to get it on WordPress.org. 
However, the premium software has dedicated software running on my servers, which will be - for both privacy and security reasons - closed.

### My main concern will always be security and performance
And this is why the premium extensions also take so much more time to set up. They don't run completely local, and I must weigh in on how often an API connection is actually required, and I must verify its integrity at all times.

### Extensions Roadmap:
[Free extensions](https://github.com/sybrew/the-seo-framework/issues?q=is%3Aopen+is%3Aissue+label%3A%22Free+Extension%22)
[Premium extensions](https://github.com/sybrew/the-seo-framework/issues?q=is%3Aopen+is%3Aissue+label%3A%22Premium+Extension%22)

There are some planned behind the scenes, which will be made public when I can clear their requirements and possibilities.

## Setting up FAQ's
...and the like. These things take up loads of time, of which I currently rather spend in building 2.8.0 and 2.9.0. Thereafter more extensions will rapidly follow 😄. If I ever were to find the time to document everything... I'd then even rather automate the documentation. Nevertheless, I hope my scattered data will suffice for now. I should definitely need to pick this up and store it somewhere, someday.

P.S. About the following, please don't. I hope I clearly stated why in one of your [linked-to posts](https://wordpress.org/support/topic/not-all-topics-are-allowed-here-read-me-before-posting/) 👍 
> but if you want I can repost this on wordpress plugin discussion site.

**Comment by LeBaux** [comment]
> You can view all available extensions right from your dashboard, both free and premium.
FAQ material right there. 🥇

As for the fragmentation in communication goes, I think you should redirect everything from wordpress plugin support here, maybe use [gitter](http://gitter.im/), and FAQ on the homepage are a must. But that is just me :)

> What does make a big difference is that the Monitor extension, for example, took me 3 months to set up, and it's still far from finished. The server software of which is 18000 lines and counting, it requires a database, hardened security, exception handling, parsing of data, etc.

This is actually quite puzzling for me - why spend so much time on very complex extension, while it is far from core functionality? Is it because you wanted to lay down foundation for the future and delivery of the premium features, requiring API? It is not really my business, so you don't have to answer if you don't feel like it.

Thanks for the granular answer, lately I am running into developers like you, willing to take time for BFU questions and it just makes me so happy. I hope you will will stay strong! Also about the Tesla comment - I am aware you are pumping precious time into this, and I appreciate it deeply. I am testing TSF on 2 sites now, if everything goes smoothly I will go for the premium. Maybe I can also lend a hand with some arbitrary task within the project at hand? I worked with a few devs and I know most of you hate documentation, blogging and marketing so if you have some small tasks in this field, hit me up, because this is what I do for food on daily basis. Also, I want that car too! 💯

**Comment by sybrew** [comment]
Hi @LeBaux,

## FAQs
Well, I do have FAQs 😄, both of which are more highlighted in the upcoming Plugin Directory:
[TSF FAQ](https://wordpress.org/plugins/autodescription/faq/)
[TSFEM FAQ](https://wordpress.org/plugins/the-seo-framework-extension-manager/faq/) (needs refinement)

I'm going to add that which you've highlighted to it in the next update :). I also need to fix some sentences, I noticed.

## The complex API explained
> This is actually quite puzzling for me - why spend so much time on very complex extension, while it is far from core functionality? Is it because you wanted to lay down foundation for the future and delivery of the premium features, requiring API?

Exactly, it is a foundation plugin to see how far I could go with the API. Now that that has been highlighted and is all working, I can use it for other projects too.

The main deal with this foundation is that it's extremely scalable. There's a proxy forwarding all the requests, and checking if it's authorized. Much like Cloudflare's DDoS firewall. From there it can choose to spread its requests in either a round-robin fashion, or pre-determined (e.g. 100 users are on one server, and 100 users on another). I wish to do this with Microsoft Azure.

The back-end can go even further, it can off-set databases, processes, etc. 
It's all based on cron-jobs, so that the user interacting with it won't notice any lag and will receive the data when it's processed and ready.

There are quite a few possibilities with these systems. Like mass-cropping images so one image will fit perfectly in Twitter, G+, Pinterest and Facebook alike. Such process can be handled easily by a dedicated server, but it will most likely fail on a shared instance.
Also, not every server has all the available image editing tools (like the [GD library](http://php.net/manual/en/book.image.php)). So we can easily move dependencies around.

I'm also an self-proclaimed expert in hosting, it's what I did before building plugins. So I think I can shed off that experience in these applications, so the users can do whatever they wish at lightning speed.

I hope this solves your puzzle 😄.

## About hiring
Regarding your offer: I simply can't afford anyone at this moment; this is essentially the deal with Open Source: we do it for free :). Wikipedia, WordPress and even the author of Contact Forms 7 can live on donations, but that's possible only when you deal with millions of users.

### Planned docs
Until then, I really need to automate my documentation! I'm already preparing all my code for that, if you look very closely in the code you'll see that every single method and function has a lot of documentation. This can be automatically pulled and put into a dedicated website.
See this one for example, which is auto-generated: https://developer.wordpress.org/reference/functions/wp_parse_args/

If you have any more questions unanswered, feel free to ask! Cheers :)

**Comment by sybrew** [comment]
The differences between Premium and Free have been outlined clearly for some time now on this page: https://theseoframework.com/pricing/.

The API is available here: https://theseoframework.com/docs/api/.

Automated documentation is still planned. The code is already compatible with this thanks to the extensive application of PHPDoc DocBlocks.

This issue doesn't pertain to the state of this project anymore, and some of it is outdated, so I'm closing it.
