### ISSUE TITLE
Opengraph tags are printed with needlessly high priority

### ISSUE THREAD

**Issue by LariElovainio** [sybrew/the-seo-framework#671]
The plugin prints the meta tags in the `wp_head` hook with priority 1. This puts the tags above most items, including theme styles, in the markup order. As far as I can tell, there is no reason to do this, and it would be better for page load performance to place the them lower.

**Comment by sybrew** [comment]
Hello! I appreciate your concern about TSF's performance.

The low-priority output is intentional and has a good reason.

I've seen sites that paste CSS high up, but instead of just a few custom lines, they dump many kilobytes of CSS in the head.

However, some platforms interpret only a webpage's first few thousand characters. So, when excessive amounts of CSS are printed in the head, TSF's meta tags become inaccessible to those platforms. We had numerous issue reports about sharing behavior when we still used priority 10.

Concerning performance, browsers must first parse the HTML DOM to display a website. The DOM could be constructed in chunks, but it's more likely that the entire HTML document has arrived before parsing happens (especially thanks to today's 4G and even fiber-based internet). So, it won't matter if the CSS is before or after TSF's meta tags. Moreover, TSF's meta tags are not render-blocking.

In the image below, I marked the stages with numbers, from which we can assume the following:
1. HTML: This is where TSF's meta tags are.
2. Render Tree: This is where the DOM is fully constructed and considered for display.
   - At this point, TSF's tags are always fully parsed in the DOM, whether they are outputted early or late. They won't have an impact hereafter.
3. Style: This is where CSS tags are being interpreted in relation to the DOM.
4. Display: Actual pixels become visible on your screen.

![image](https://github.com/sybrew/the-seo-framework/assets/7662236/1132b077-7459-46ec-a038-f96ec4b94a01)

To learn more, see https://web.dev/learn/performance/understanding-the-critical-path#the_critical_rendering_path.

I hope this explains everything well. Feel free to let me know if you still have questions. You could try to change the priority and see if it has an actual performance impact, but I highly doubt this to be the case, given how the critical rendering path works.
