### ISSUE TITLE
5.1.0 Uncaught TypeError: URL.parse is not a function

### ISSUE THREAD

**Issue by ktmn** [sybrew/the-seo-framework#698]
**Describe the bug**

JS error when editing a post after updating to the latest plugin version:

```
canonical.min.js?ver=5.1.0:1 Uncaught TypeError: URL.parse is not a function
    at d (canonical.min.js?ver=5.1.0:1:693)
    at HTMLInputElement.f (canonical.min.js?ver=5.1.0:1:884)
    at e (canonical.min.js?ver=5.1.0:1:808)
    at h (canonical.min.js?ver=5.1.0:1:1033)
    at canonical.min.js?ver=5.1.0:1:1157
```

**How to reproduce the bug**
1. https://playground.wordpress.net/?plugin=autodescription&url=/wp-admin/post-new.php&mode=seamless
2. Error is in console (maybe)

**Additional context**

Happens with Chrome but not Firefox for me. I don't know when this function is supposed to be available or not, but the docs include `if ("parse" in URL) {` in the example so I guess it's common to not be available.

https://developer.mozilla.org/en-US/docs/Web/API/URL/parse_static

The metaboxes seem to be working despite the error, so it's not critical.

**Comment by sybrew** [comment]
Hi @ktmn, thanks for reporting this.

`URL.parse()` is a relatively new function in browsers.
You can find out which version you're using by going to this URL: `chrome://version`.

You will get the error if you're using Chrome 125 or below.
See https://caniuse.com/mdn-api_url_parse_static.

Since I assumed that people automatically upgraded Chromium-based browsers, I didn't consider it an issue. 

The rest of TSF's interface isn't crashing thanks to this change: https://theseoframework.com/changelog/5-1-0-profound/#::text=If%20a%20settings,for%20social%20sharing. I'm glad to learn it's already doing its job well 😃.

I don't think I will resolve this issue unless something prohibits people from updating their browsers.
