### ISSUE TITLE
include_compat() is not accessible

### ISSUE THREAD

**Issue by kamilgrzegorczyk** [sybrew/the-seo-framework#74]
Hey,

After upgrade to 2.8.0 there is an error thrown:
`Error: the_seo_framework()->include_compat() is not accessible. In /var/www/bdswiss-wp/web/app/plugins/autodescription/inc/classes/admin-init.class.php on line 69.`

I believe that this is caused by a simple typo on this line:
https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/compat.class.php#L61

If there is a need I can submit a pull request with a fix for this issue.

**Comment by sybrew** [comment]
Submitting 2.8.1 ASAP. This will cause fatal errors. Thanks for this!

P.S. You should really enable multibyte strings (mbstrings) for your PHP install, it's about 2000x faster with this plugin, as we do all the string manipulation through multibyte calculation. It will also help WordPress internally, especially since the WP 4.2 Emoji update.

The error you got is because a) I made a typo and b) your server doesn't support mbstring, so we need compatibility functionality; which is very heavy to do on PHP, rather than C: https://github.com/sybrew/the-seo-framework/blob/master/inc/compat/php-mbstring.php

http://php.net/manual/en/book.mbstring.php

**Comment by sybrew** [comment]
Affected actions that will crash:

1. Feed excerpt generation when WordPress doesn't make an excerpt out of it:
https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/feed.class.php#L103

2. Title generation, when your title is doing it wrong:
https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/generate-title.class.php#L393-L396

So the effects are luckily quite minor :)

**Comment by sybrew** [comment]
Could you test https://github.com/sybrew/the-seo-framework/commit/24e75350e21621792a864a317fcc4dbd3c328e73?

https://github.com/sybrew/the-seo-framework/archive/master.zip

Cheers!

**Comment by kamilgrzegorczyk** [comment]
Hey, yes it fixes the issue. Thank you ;)

One problem is that In the project I use your plugin I install all the plugins via composer/wp-packagist. As I use your plugin for more than a year I see that You are not tagging every version (2.8.1 is not tagged as well, https://downloads.wordpress.org/plugin/autodescription.2.8.1.zip serves 404). Why? ;)

**Comment by sybrew** [comment]
😲 I do tag every version, but not directly; mostly because I'm too tired/lazy after the master push and testing if that's going well. 
Also, I didn't know it had an impact? I could tag more quickly if you wish.

Also, suggestion for the packaging software: 😄 
`dl = httpOKfunc( 'autodescription.2.8.1.zip' ) ?: httpOKfunc( 'autodescription.zip', 'master/true' );`

**Comment by kamilgrzegorczyk** [comment]
No tag means composer will fail fetching it from repo so its an issue for all of us using composer.

regarding the suggestion -> composer keeps it configuration in json so no function calls there ;)

**Comment by sybrew** [comment]
Uploading tag as I write this. I'll be sure to make it a more speedy process in the future.

Cheers :)
