### ISSUE TITLE
Extra separator / space overwriting manually set title tags

### ISSUE THREAD

**Issue by jamesfacts** [sybrew/the-seo-framework#81]
I'm a big fan of The SEO Framework and have used it on several sites in the past without issue. Unfortunately, I've run into a weird issue after an install today—title tags have gone all wonky. All my manual title tag data was imported from Yoast 1.6 and looks totally normal inside the WP admin view on a single post.

My homepage has no title tag at all:
http://thebaffler.staging.wpengine.com/

On a number of posts, the manually set title tag is trimmed, then appended with a whitespace, pipe, and three more whitespace chars. 
So, here: http://thebaffler.staging.wpengine.com/blog/chelsea-manning-existential-threat-madar

Custom blog title field contains this info:
"Chelsea Manning’s Existential Threat to American Innocence | Chase Madar"

...but it displays as:
`<title>Chelsea Manning’s Existential Threat to American Innocence | Chase Mad | 		</title>`
 
If the custom blog title is short enough, it's just appended with the extra separator and white space.
http://thebaffler.staging.wpengine.com/blog/drone-frost
`<title>Office-Droned Out | Amber A&#8217;Lee Frost | 		</title>`

Any idea what's gone wrong? Ideally there will be nothing—no blog title, no separator, etc, past the manually set custom blog title.

**Comment by sybrew** [comment]
Hi @jamesfacts, 

Awesome! Thanks :)

I'm afraid your site requires a title fix, it's delivered through an extension which is included for free in this plugin:
https://wordpress.org/plugins/the-seo-framework-extension-manager/

If the that works, it's a theme issue; where the `<title>` tag is handled poorly.

If you're a developer, I'd suggest creating a child theme where you delete the manual title tag from the `header.php` file and inject the title-tag support through: `add_theme_support( 'title-tag' );` in the child-theme's `functions.php` file.
If that's done, you can disable the title fix extension.
More info on this issue is found here: https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/

Best of luck 😄

**Comment by jamesfacts** [comment]
You're a star. That did exactly the trick—thanks a million.
